### ISSUE TITLE
[BUG] Wintergrasp Heirlooms not giving hit rating, other stats

### ISSUE THREAD

**Issue by sunbatherr** [JamminL/wotlk-classic-bugs#461] opened 2022-10-12 09:00 UTC
#### 1.1. Description
Heirloom items are not giving their secondary stats (crit, hit, etc.) properly. Wintergrasp Heirlooms for sure, possibly badge ones. 
  #### 1.2. How to Reproduce
          1. Equip Wintergrasp Heirloom
          2. Observe hit rating
  #### 1.3  Source Material
  Image: https://i.imgur.com/zilnByc.png

**Comment by CharWS** [comment] 2022-10-12 09:03
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/440
can move additional info there to keep things tidy

**Closed by CharWS** 2022-10-12 09:03 UTC
Labels: Pending Approval
