### ISSUE TITLE
[BUG] Melee attacks delay next ranged auto-shot by some amount

### ISSUE THREAD

**Issue by chloanne** [JamminL/wotlk-classic-bugs#264] opened 2022-08-06 09:25 UTC
#### 1.1. Description

Currently, performing a melee auto-attack delays the next ranged auto-shot performed by some amount. This, in conjunction with #106 is making it impossible to melee weave as a hunter, even with a sufficiently-fast melee weapon. The amount of delay incurred seems to be very long, perhaps equal to a full ranged timer reset.

  #### 1.2. How to Reproduce
```
1. Move into melee range
2. Perform a melee auto-attack
3. Quickly move to range
4. Attempt to perform an auto-shot
```
#### 1.3  Source Material

https://streamable.com/rn17w4

#### 2.1. Description
According to the closure message in #81, melee attacks should not delay auto-shots. This was the behavior originally observed on the beta. Step 4 (perform an auto-shot) should happen instantly, with no delay.

  #### 2.2 Source Material

> Currently on the beta - there is a new interaction with this where melee delays the next ranged attack. This is indeed unintended.

**Comment by yurpcraft** [comment] 2022-08-09 15:30
Closing as duplicate of somechanges suggestion #258

**Comment by chloanne** [comment] 2022-08-09 18:09
@yurpcraft You've misunderstood -- this is a bug report, not a suggestion for changes. The beta is currently behaving differently from the expected/authentic behavior of original wrath.

**Comment by yurpcraft** [comment] 2022-08-09 19:15
Updated description for clarity

**Comment by Aggrend** [comment] 2022-08-13 01:01
This is NAB. I commented on #81, but according to our research (and a task in our database from 2008), this is also correct behavior. 

Summary of that task (taken directly from our Task DB from wrath-era):
Modify the auto-attack swing timer system to cause melee and ranged auto-attacks to enforce swing timers on both types of attacks.

**Closed** 2022-08-13 01:02 UTC
Labels: Hunter, BUG
