### ISSUE TITLE
[BUG] Aura range is not correct

### ISSUE THREAD

**Issue by Undertoe** [JamminL/wotlk-classic-bugs#422] opened 2022-09-20 14:23 UTC
#### 1.1. Description
Currently, auras have about a 36-38 yard range.  This can be tested by
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Move to just out of healing range
           2. Take a small step forward so you're just in healing range (~40 yards)
           3. Note that you can heal the target, but they are not in aura range.
#### 2.1. Description
  Auras should have a 40 yard range, and you should be able to hit anyone with them if you can heal them.  

It's entirely plausible this could be a bug with aura type effects as a whole and may need to get checked on other abilities.  It could be that aura radius is calculated at the center of the thing generating the aura rather than the edge (This seems most likely to account for the distance seen). 

As a note, tooltips are also saying 30 yards in game when  other things are saying 40.
![image](https://user-images.githubusercontent.com/3249986/191283844-27d5b28e-079f-43ec-8a1c-aa7edfe6cd1b.png)
https://www.wowhead.com/wotlk/spell=27149/devotion-aura

**Comment by watchyoursixx** [comment] 2022-09-20 14:41
I'm not so sure this is a bug, it may have been like this the whole time.

I did a bunch of testing back in vanilla classic because the hunter deadzone said it was 5-8 yards, which implied it was only 3 yards to travel. However, after much testing and investigation the conclusion was made that the dead zone was actually 5-11 yards or more specifically approximately 5 - 10.66 yards. 

All abilities that are considered not melee have an inherited "combat range" for lack of a better phrase. This was based on the players hitbox and was larger for tauren. This is why tauren could attack targets from a greater distance more than just melee attacks.

Auras, and aoe effects centered around the character did not have this effect if I recall correctly. I'll have to do some digging for some examples but there was some extensive testing back in 2019.

Since this is a core function of how the game played, I don't expect that this would have changed but I could be wrong.

Note that this is not to be confused with leeway caused by movement.

**Comment by watchyoursixx** [comment] 2022-09-20 14:44
I'm not so sure this is a bug, it may have been like this the whole time.

I did a bunch of testing back in vanilla classic because the hunter deadzone said it was 5-8 yards, which implied it was only 3 yards to travel. However, after much testing and investigation the conclusion was made that the dead zone was actually 5-11 yards or more specifically approximately 5 - 10.66 yards. 

All abilities that are considered not melee have an inherited "combat range" for lack of a better phrase. This was based on the players hitbox and was larger for tauren. This is why tauren could attack targets from a greater distance more than just melee attacks.

Auras, and aoe effects centered around the character did not have this effect if I recall correctly. I'll have to do some digging for some examples but there was some extensive testing back in 2019.

Since this is a core function of how the game played, I don't expect that this would have changed but I could be wrong.

Note that this is not to be confused with leeway caused by movement.

**Comment by watchyoursixx** [comment] 2022-09-20 14:51
As to your example of devotion aura, I think the more accurate description would be "auras are 40 yd while abilities that say 40 yd are actually greater"

I bet that if you timed the distance from player 40yd aura range to target player center, at the given yd/s speed of 7 yd/s. It should take 5.71 sec to run that distance. The expected distance at max range of healing would be approximately 42.66 from player max range to target player center, or 6.1s of travel.

This should be noticable enough to confirm whether it's the aura or the targeted spells that are "off" and I suspect the actual distance is like I mentioned, not shorter than expected

**Comment by Oliaxz** [comment] 2022-09-20 16:59
In your test, its important to note if both player were at a dead stop for more than 5seconds because of the following reasons

1. AoE Aura batch. Basically, it can take up to 5s for an aura to register/fade. Like flare/trap not fading when you move out. source : https://github.com/JamminL/wotlk-classic-bugs/issues/124
2. Targeted spells have a leeway mechanic. I think its around 2.66 extra yard, and the requirement for that extra range is one player must be moving, and both player must have no speed reduction. Thats why if one player backpedals, the leeway range is removed. And tauren had extra range because their hitbox was larger, but hitbox is normalised in wotlk.

So anyway, if both player are stopped for more than 5s, devotion is not registering but you can heal, then i agree that theres something off there.

**Comment by caccavale** [comment] 2022-09-20 20:05
This seems to stem from player centered AoE ranges being radius from the player's center while targeted spells use (near-)edge to (near-)edge distance.  Likely NAB.

**Comment by watchyoursixx** [comment] 2022-10-30 15:37
closing as NAB unless some new evidence proving otherwise

**Closed by watchyoursixx** 2022-10-30 15:37 UTC
Labels: General, Paladin, Research Needed
