### ISSUE TITLE
[BUG] Earthen Power (enha talent) sometimes doesnt dispel all the slows

### ISSUE THREAD

**Issue by traktorcho** [JamminL/wotlk-classic-bugs#475] opened 2022-10-16 11:42 UTC
#### 1.1. Description
What the talent states is that it has 100% chance to dispel all slows on you and your party members with each earthbind tick which ticks instantly on usage but sometimes it only dispels 1 of the slows instead of all
  #### 1.2. How to Reproduce
          Duel a rogue make him backstab you and use crippling poison use earthbind and it should dispel only 1 of the debuffs and you will remain slowed still
  #### 1.3  Source Material
https://www.twitch.tv/videos/1625170216
You can clearly see how i use earthbind totem and i only dispel mage armor slow but the enemy earthbind slow still remaining
### 2. Expected Behavior
It should dispel all slows on you not just one.

**Comment by diamondsprings** [comment] 2023-03-05 15:53
gonna bump this and provide some additional info as it's still bugged, and it's very much significant because it's the main part of enhancement shaman's mobility kit and it just kinda half-works. because of this bug it's now a common strategy to abuse it by just spam stacking slows (e.g. hamstring and piercing howl, frost shock and earthbind, etc.) so you can't ever get rid of them. it should be noted that it is not only "sometimes" as the title says, earthen power can't dispel more than one slow ever, so you should be able to reproduce it every time with the steps traktorcho has provided here or with any other 2 (or more) slows.

now, as far as i'm aware, there is not a single spell available to players that is worded anything even remotely similarly that does *not* remove everything. and there's a lot of them, so let me show some examples.

[Earthen Power (the spell in question):](https://www.wowhead.com/wotlk/spell=51524/earthen-power) **"remove all snare effects"** - removes one snare

[Blazing Speed (mage):](https://www.wowhead.com/wotlk/spell=31642/blazing-speed) **"dispel all movement impairing effects"** - removes all as advertised
[Spirit Walk (shaman):](https://www.wowhead.com/wotlk/spell=58875/spirit-walk) **"removes all movement impairing effects"** - removes all as advertised
[Master's Call (hunter):](https://www.wowhead.com/wotlk/spell=53271/masters-call) **"remove all root and movement impairing effects"** - removes all as advertised
[Dispersion (priest):](https://www.wowhead.com/wotlk/spell=47585/dispersion) **"clears all snare and movement impairing effects"** - removes all as advertised
[Demonic Circle: Teleport (warlock):](https://www.wowhead.com/wotlk/spell=48020/demonic-circle-teleport) **"removes all snare effects"** - removes all as advertised, exact same wording
[Vanish (rogue):](https://www.wowhead.com/wotlk/spell=26889/vanish) **"breaks movement impairing effects"** - removes all as advertised
[Warbringer (warrior):](https://www.wowhead.com/wotlk/spell=57499/warbringer) **"remove all movement impairing effects"** - removes all as advertised

there are more examples than this but you get the point. i can't find one that's similarly worded but only dispels one, so this seems like a pretty clear bug to me.

**Comment by Totemclass** [comment] 2023-04-12 21:22
https://github.com/JamminL/wotlk-classic-bugs/issues/655. I'd like to add my extensive write up of this issue to this post in hopes that it brings more attention and awareness to this extremely gamebreaking issue. Within the link provided there is an active video recording of the bug mentioned that isn't locked behind a twitch subscription, and a comprehensive write up which can hopefully be used in tandem with these reports from Traktorcho and Diamondsprings.

**Comment by raethkcj** [comment] 2023-06-09 20:06
Based on a recent development build, it appears Blizzard will be changing the tooltip on this talent to match its behavior, rather than changing the behavior to match the existing tooltip:

https://wago.tools/db2/spell/diff?from=3.4.2.49871&to=3.4.2.49979

**Comment by JamminL** [comment] 2023-10-12 21:32
Fixed as of last patch

**Closed by JamminL** 2023-10-12 21:32 UTC
Labels: Shaman, BUG, Fixed
