### ISSUE TITLE
[BUG] Rune mixmatch in classic beta

### ISSUE THREAD

**Issue by 1ps3** [JamminL/wotlk-classic-bugs#181] opened 2022-07-23 14:02 UTC
#### 1.1. Description
  At the moment runes 5&6 are return rune type 2 when using the GetRuneType() call and runes 3&4 return rune type 3. When using spells that would consume frost runes, runes 5&6 are used which has historically been the unholy rune slot and type. This seems to be changed in classic wrath, it's not a real bug just something that might trip a few people over. 
  #### 1.2. How to Reproduce
  Dumping the GetRuneType and GetRuneCooldown in game.
#### 2.1. Description
 The expected behaviour would have runes 5&6 and rune type 2 be unholy while runes 3&4 would be type 3 which is frost.
  #### 2.2 Source Material

**Comment by fabbew** [comment] 2022-07-23 14:41
Like the OP states its not a bug.

This has been the case for a long time and **should not be changed**, it adds nothing to change, is obvious for anyone interacting with the API and reading the documentation on for example wowpedia, where you can clearly see the excepted return values. 

https://wowwiki-archive.fandom.com/wiki/API_GetRuneType

>     runeType - The type of rune that it is.
> 
>         1 : RUNETYPE_BLOOD
>         2 : RUNETYPE_CHROMATIC
>         3 : RUNETYPE_FROST
>         4 : RUNETYPE_DEATH
> ("CHROMATIC" refers to Unholy runes) 


This is asking for trouble by messing with it. Imagine everything it will break for everyone who have read the API/tested it. If it works don't fix it.

**Comment by caccavale** [comment] 2022-07-23 14:44
OP is talking about the parameters given to the function.  Right now on classic, 1,2 are blood runes, 3,4 are unholy runes, 5,6 are frost.  This order doesn't align with the order on the player frame.  Is this consistent with how it was on retail wotlk?

**Comment by caccavale** [comment] 2022-07-23 14:54
Just checked a 3.3.5 version of RuneHUD which suggest this issue existed in original wrath.  Closing as NAB.

**Comment by fabbew** [comment] 2022-07-23 14:54
> 


If you just go to https://wowpedia.fandom.com/wiki/API_GetRuneType?oldid=1686730 you can see that it has been the case from november 2008, until it was removed when Blizzard removed individual rune types. This means that any addons attempted to be ported over from then or anything that has been written so far will need to be changed. Worse any code out there will be incorrect for future developers.

**Closed by caccavale** 2022-07-23 14:54 UTC
Labels: Pending Approval

**Comment by 1ps3** [comment] 2022-07-23 15:07
That's interesting. I never noticed that even back then, though I didn't interact much with the rune API since there wasn't much need. The only reason I brought it up was because of the wowpedia page that you linked, it states that rune type 2 should be RUNETYPE_CHROMATIC which is unholy. Runes 5&6 do give a runeType of chromatic, though they are consumed by frost spells. 

Though if this was the case back then there's no real reason to change it, perhaps one should just update wowpedia to mention that.
