### ISSUE TITLE
[BUG] Retaliation vs Retaliation bugged

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#259] opened 2022-08-05 08:08 UTC
#### 1.1. Description
If you Retaliation vs Retaliation one of the warriors will die almost instantly
  #### 1.2. How to Reproduce
           1. Duel a warrior as a warrior and both press Retaliation
           2. Attack each other
  #### 1.3  Source Material
https://gyazo.com/00a4c89f10c95a18f4f9edc609a0c00b
#### 2.1. Description
A counter-attack from retaliation shouldn't proc another one
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment] 2022-08-08 17:17
https://youtu.be/3cGqlcE44m0?t=415 retal attacks do proc others but at a way slower pace, maybe there was an ICD? not sure, I have another clip if this isn't enough. 

If anyone cares to go through this video and break it down lmk :)

**Comment by MuffledBaneMask** [comment] 2022-08-11 21:18
With the removal of 400ms batching, interactions such as Retaliation get to occur more quickly. Retaliation is working the same way in the youtube clip but everything in the game is being processed more than 20x slower, so any loops or recursive moments are more dramatic in a world where they ping back and forth every 10ms instead of every 400ms.

**Comment by Aggrend** [comment] 2022-08-12 22:58
Confirming what Ghost said is correct. This is victim of the removal of the 400ms batch window. As with other minor interaction changes due the reduction of the batch window we won't be making a lot of large changes to specific abilities or interactions to account for that, in most cases. This can be closed as Not A Bug.

**Closed** 2022-08-12 23:01 UTC
Labels: Warrior, BUG
