### ISSUE TITLE
[#SomeChanges Suggestion] Remove Nitro Boosts in Arena

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#361] opened 2022-08-27 17:54 UTC
Guesswork when evidence is already available is one of the reasons WoW has become a sinking ship for a decade. Re-read that. We don't need to assume players want things when they've already been tried & tested. 

WotLK and Vanilla are by far the most popular WoW versions to date, backed up by emulation statistics. Players of all experience levels spoke up when changes were made to Blizzard's relaunch of Vanilla that weren't in tune with what they wanted, and we're now doing the same thing for Wrath.

One of the sole reasons private servers are popular is because they're made by players who want to play a game that isn't available anymore, which makes them a lot more in tune with the community and it's wishes. They aren't restricted by everything a massive company like Blizzard is re development and game choices, so please listen to the thousands of fans that have been passionately playing this game for years.

You've got loads of people here who have been playing this game for years, of all levels, trying to help you understand where you may not, what the general playerbase wants and filling in the gap for where they may not understand yet, with evidence and logic. We don't need a willynilly "whatever bro let's just throw this in and we'll see if they like it". Terrible way to poison a game that's already established. With a new game, sure. Not with Wrath.

Private servers don't have nitro boosts in Arena because the hundreds of thousands of people playing them, don't want them. It's not rocket science. Absolutely absurd speed boost on tiny little maps where the deciding factor on whether you win is if you kill the enemy. It's a small scale deathmatch. What happens when you give melee classes a tool like this to connect on someone without an escape? It's also not as simple as "well everyone has it!" because some classes can clear slows, snares and stuns where others can't, so they will exponentially scale better with a speed boost that allows you to clear entire maps in seconds, much better than the classes that don't.

Please reconsider. Don't turn this game into a clown show. You have a chance here with Wrath to show the world you still care about this product.

**Comment by CharWS** [comment] 2022-08-27 18:00
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/359

**Closed by CharWS** 2022-08-27 18:00 UTC
Labels: #SomeChanges Suggestion
