### ISSUE TITLE
[BUG] Living bomb - combat

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#471] opened 2022-10-15 12:31 UTC
#### 1.1. Description
The explosion of a living bomb does not bring the target and the caster into combat
  #### 1.2. How to Reproduce
           1. Press Living bomb
           2. Wait for the explosion    
  #### 1.3  Source Material
https://imgur.com/a/FYnzRVZ
#### 2.1. Description
After fixing Blizzard, no longer enters combat. This is the wrong fix. The explosion from the living bomb should bring the caster and target into combat
  #### 2.2 Source Material
https://www.warcraftmovies.com/movieview.php?id=154367 @24:46
https://www.warcraftmovies.com/movieview.php?id=165253 @14:09
https://youtu.be/x-MYh2kfO90?t=253

**Comment by JamminL** [comment] 2022-10-15 13:48
duplicate of #445

**Closed** 2022-10-15 13:48 UTC
Labels: duplicate
