### ISSUE TITLE
[BUG] Earthen Power (Enhancement Shaman Talent)

### ISSUE THREAD

**Issue by Totemclass** [JamminL/wotlk-classic-bugs#655] opened 2023-04-12 03:59 UTC
#### 1.1. Description
Earthen Power, a deep enhancement shaman talent is not functioning properly in its current state. The text for this talent reads - “Your Earthbind Totem’s pulses have a 50% chance to also remove all snare effects from you and nearby friendly targets, and your Earth Shock reduces enemy attack speed by an additional 5%”, with the ability to add an additional talent point into Earthen Power to increase those previously mentioned values to allow your earthbind totem’s pulses a 100% chance to remove snare effects from the casting shaman and nearby friendly targets, while also reducing enemy attack speed by an additional 10% when applying the earth shock debuff to a hostile target, respectively.

The issue with this talent is that earthbind is NOT removing all snare effects on the casting shaman and friendly targets. Earthbind will remove one snare immediately upon placement of the totem, and then one additional snare per tick of earthbind totem from all friendly targets within range of the pulse effect. This behavior is in direct conflict with the language presented in the 2/2 talented version of Earthen Power.  

#### 1.2. How to Reproduce
1. Gather any number of friendly players and place them within the projected area of effect of an earthbind totems pulse radius from a friendly shaman with 2/2 Earthen Power talented. You can reproduce with just the casting shaman as well, but more players are advised to produce the aforementioned bug more consistently to expedite accurate demonstration of the 2/2 talented version of the Earthen Power dispel not triggering correctly and failing to dispel snares.
2. Gather a single or multiple hostile targets whom are hostile to the casting shaman and friendly targets from step 1
3. Have the hostile targets from step 2 cast multiple snare effects on the party from step 1 IE: earthbind totem, piercing howl, waylay, crippling poison, etc.
4. Finally, the shaman from step 1 should now cast earthbind totem. You should notice immediately that the casting shaman and the friendly targets from step 1 are not being cleared of their snare effects.
  #### 1.3  Source Material
With the issue being so easily reproduced using the current client of World of Warcraft: Wrath of the Lich King Classic, I've managed to create a video reproducing this issue with relatively little effort. The link attached is a clip of the bug fully reproduced using 1 friendly target and 1 hostile target applying multiple snare effects simultaneously to the friendly shaman, and right away, you are able to see how earthbind is not behaving in the intended manner. https://clipchamp.com/watch/I9M3dcpZhCV

What you're viewing in this clip are the debuffs Waylay (https://www.wowhead.com/wotlk/spell=51696/waylay) and Crippling Poison (https://www.wowhead.com/wotlk/spell=3408/crippling-poison) being applied to the Shaman and being active simultaneously. You are then able to see earthbind confirm that it has attempted to remove the snares from the shaman in two ways. Once via the swirling animation around the shaman signifying that a dispel has occurred, and also through audio cues again confirming that a dispel has taken place. After this visual and audio confirmation that the dispelling effect of the talent has occurred, you can see the Shaman continues to retain a Waylay or Crippling Poison snare until an additional dispel can be provided by the totem on the next tick. This is inaccurate. 

#### 2.1. Description 
"Earthen Power 2/2": Your Earthbind Totem's pulses have a **100% CHANCE** to also remove **ALL** snare effects from **you and** nearby friendly targets, and your Earth Shock reduces enemy attack speed by an additional 10%." This is the language associated with the talent when 2 talent points have been placed into Earthen Power, making the intended design of this talent abundantly clear. Earthbind totem should dispel snare effects upon each successful tick, which ultimately leads to the conclusion that Earthen Power 2/2 is not functioning properly in its current state.

  #### 2.2 Source Material
Snare effects persisting on friendly targets within range of the casting shamans earthbind totem's pulses should not be possible based on similar talented effects and abilities with similar wording functioning properly, clearing the target of all snares.

**Comment by CharWS** [comment] 2023-04-12 19:44
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/475

**Closed by CharWS** 2023-04-12 19:44 UTC
Labels: Pending Approval

**Comment by Totemclass** [comment] 2023-04-12 21:26
Folks being directed to this post should continue to Traktorcho's write up where I've added my findings and evidence to hopefully bring this issue to light. Thank you! https://github.com/JamminL/wotlk-classic-bugs/issues/475
