### ISSUE TITLE
[BUG] Delay to use Shield Block / Shield Wall / Shield Reflection with a macro

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#231] opened 2022-07-30 08:31 UTC
#### 1.1. Description
When you use a macro to equip 1-hand and shield and use one of these 3 spells, it takes a delay of like ~0.5sec to be able to use the spell
  #### 1.2. How to Reproduce
       1. Make a macro /equip 1hand /equip shield /cast one of these 3 spells
       2. Spam the macro
       3. Notice it's delayed a lot
  #### 1.3  Source Material
Not yet
#### 2.1. Description
It should take 2 press on the macro for the spell to be used, not around 0.5sec
  #### 2.2 Source Material
Not yet

**Comment by CharWS** [comment] 2022-07-30 08:34
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/223 if you have additional evidence or information to provide add it there

**Closed by CharWS** 2022-07-30 08:34 UTC
Labels: Pending Approval
