### ISSUE TITLE
[#SomeChanges Suggestion] Cooldown on Weapon Enchants and Meta Gems when swapped in combat.

### ISSUE THREAD

**Issue by Woffl8** [JamminL/wotlk-classic-bugs#540] opened 2022-11-22 00:59 UTC
### Description
Currently meta gems with on hit procs and enchants can be changed in combat with macros or automated with weakauras.
This has lead to unhealthy game play of cycling through metagems and weapons on boss fights giving classes that can benefit from these procs a huge extra advantage.

There is currently a weakaura out that will swap your meta gem once its ICD is off allowing you to refish for the proc, this also exists for weapons.

###Suggestion
Meta gems and enchants that have a chance on hit to proc should be put onto a ICD when changed similar to how trinkets when swapped go on cooldown.
Restrict meta gems from being changed in combat

### Examples
https://youtu.be/DXBAybT9Y2U
https://youtu.be/tfFuK0PMJ0E?t=45
Fully Automatic Metaswap WA: https://pastebin.com/6PmDgkfL

**Comment by CharWS** [comment] 2022-11-22 07:48
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/484 and https://github.com/JamminL/wotlk-classic-bugs/issues/368

**Closed by CharWS** 2022-11-22 07:48 UTC
Labels: #SomeChanges Suggestion
