### ISSUE TITLE
[BUG] STORMSHROUD

### ISSUE THREAD

**Issue by jackiechonger** [JamminL/wotlk-classic-bugs#306] opened 2022-08-15 14:40 UTC
Hello, it seems you forgot to disable this item above a certain level like you did for druid tier 4 (2 set bonus) and Wolfshead helmet, please nerf this item (or buff the others) so that your logic is sound and consistent. This armor set will 100% be abused by energy classes because of its crazy procc rates in AoE.

What is the point of nerfing some low level items that would be utilized at level 80 but leaving others open? They will be abused anyway, thank you.

**Comment by watchyoursixx** [comment] 2022-08-15 15:20
If you're going to leave a issue please use the correct format.

If you believe this to be bugged use the "bug" issue and fill out the relevant info as best you can. If you can find sources that is best but even just some kind of reference of what you think it should be based on patch notes or historical references would be helpful.

If this is not a bug and is the same as wotlk original, then please fill out a #somechanges issue instead.

Gonna close this. Please open an issue properly formatted with one of the above.

**Closed** 2022-08-15 15:20 UTC
Labels: Pending Approval

**Comment by caccavale** [comment] 2022-08-15 15:37
If wolfshead is not giving energy on beta right now, please source some expected behavior and bug report it.
BUG tickets are for diverging beta and original WotLK behavior; use SomeChanges tickets for "fighting for consistency."
