### ISSUE TITLE
[BUG] Using Death Runes in conjunction with Death Rune generating spells converts different runes into Death Runes.

### ISSUE THREAD

**Issue by NuptupTDOW** [JamminL/wotlk-classic-bugs#322] opened 2022-08-18 22:23 UTC
### 1. Current Behavior
   (This is a continuation of my comment to bug report #86 where I explained an additional layer of issues regarding Death Runes.)

  #### 1.1. Description
   When consuming death runes, other non-converted runes of the correct type will be converted to death runes while they are on cooldown. 
   Example: using 2 death runes that were originally blood runes to cast death strike while all frost and unholy runes are on cooldown and not death runes, will cause one frost and one unholy rune to convert into a death rune mid-cooldown.

  #### 1.2. How to Reproduce
   1. Talent into Death Rune Mastery and either Blood of the North or Reaping.
   2. Cast Blood Strike Twice, converting the blood runes into death runes.
   3. Cast Icy Touch and Plague Strike Twice, putting all 4 frost/unholy runes on cooldown.
   4. Pay attention to the 3rd and 5th runes (1st frost and 1st unholy) and cast Death Strike using the 2 (blood) death runes.
   5. Note that the frost and unholy runes will have both converted into death runes as if they had been used to perform the attack.

  #### 1.3  Source Material
   Will post one when I get home in about 7-8 hours. (If not needed, please let me know. )

#### 2.1. Description
   Only the runes actually spend to use the spell should be converted to death runes. 
 
 #### 2.2 Source Material
   I do not have a link to an old video, but can find one if necessary. It seems pretty irrelevant though.

#### 3.1. Description
   In addition to that issue, I am almost entirely certain that when you perform an attack that converts runes into death runes **using** death runes, those runes return to their original type instead of "re-converting" back into death runes. I can't confirm this behavior right now, but I will search for an old video that might demonstrate this interaction. My reason for believing this is because I don't remember ever being able to infinitely chain Death strikes or Obliterates by converting my blood runes into death runes, and then only casting Death Strike or Obliterate from there except to re-up diseases. 
 
 #### 3.2 Source Material
   I will search for a video demonstrating this and link it in a follow-up comment or ask a friend to test it in a 3.3.5 environment. (If not needed, please let me know. )

**Comment by caccavale** [comment] 2022-08-19 00:38
Can't speak to the first part of your issue but the additional issue 3 is not a bug afaik and working as intended.  If you can find proof otherwise we'd welcome it though.

**Comment by NuptupTDOW** [comment] 2022-08-19 03:47
> the additional issue 3 is not a bug afaik and working as intended. If you can find proof otherwise we'd welcome it though.

So, I will definitely be looking for a video as proof when I get home, however I want to bring attention to the actual text for the talents that specifies (for Death Rune Mastery) ". . . a 100% chance that the _**Frost and Unholy Runes**_ will become Death Runes when they activate." and (for Blood of the North and Reaping) ". . . a 100% chance that the **_Blood_** Rune [becomes|will become] a Death Rune when it activates." There's a very slight wording difference, but they all seem to specify that the Frost|Uhnoly or Blood Runes spent for applicable spells will become Death Runes upon activation. 

The last sentence also states that "Death Runes count as a Blood, Frost or Unholy Rune." which could be interpreted as cyclically benefitting from the talents which generate them as well, however it seems clear that it is intended to only _**count**_ as those types for consumption calculations during usage, and not be _**treated**_ as them indefinitely. 

Again, there are two separate readings for this talent that could imply either direction, but, having spent 875+ **days** logged in as my death knight between Wrath, Cata and MoP during their retail launches, I am almost entirely certain it is not supposed to work that way. I will do some searching when I get home to find a video to compare it to from back then to be sure. 

Anyway, I want to thank you for being so quick to respond, both here and to issue 86. You guys are the heroes we need!

**Comment by NuptupTDOW** [comment] 2022-08-19 05:51
> If you can find proof otherwise we'd welcome it though.

https://youtu.be/X6lO6fJCxNg

Boom Baybee! Here's the video I made detailing the interaction. As you can see in the video, My additional issue 3 is clearly on display there. Here's hoping it can also get fixed as it currently allows for rotations that were never possible, unintentionally increasing the output of dk's both in terms of hps or dps.

**Comment by Cleavis** [comment] 2022-08-19 13:31
I strongly suspect this is NAB. OP if you can find source material for section 2.2 here, that would help a lot.

Just to clarify the additional issue, the video you linked most recently in the reply is from 3.3.5 pserver, correct? And you are describing your expected behavior. Which helped me understand the issue a bit, but just to clarify the obvious: a private server reference is not 3.3.5 source material. I am not seeing behavior on the beta that would allow DKs to "infinitely chain Death strikes or Obliterates."

**Comment by caccavale** [comment] 2022-08-19 14:16
Pushing this back to pending until we have a reference for expected behavior.

**Comment by Cleavis** [comment] 2022-08-19 17:51
To explain why I think this is NAB, here is DRM working on 'unspent' runes - https://youtu.be/jE8Hq1mqzio?t=185

BBDDuu, casts death strike w DD, converts to BBdfdu (instead of BBdduu as issue might expect, or BBdfuu) -- converted u rune was not spent on death strike.

this matches beta behavior for DRM -- https://youtu.be/ZRYEjU6TCZ8 (me on dummy casting death strike w frost runes only, converts an unholy rune to death. beta 45189)

**Comment by JamminL** [comment] 2022-08-19 17:53
Closing as NAB, if evidence is found of the contrary please post it here

**Closed by JamminL** 2022-08-19 17:53 UTC
Labels: Death Knight, Not a Bug
