### ISSUE TITLE
[BUG] Equipment Manager Broken - Inaccessible sets

### ISSUE THREAD

**Issue by thomas-parrish** [JamminL/wotlk-classic-bugs#453] opened 2022-10-08 11:59 UTC
#### 1.1. Description
           The Equipment Manager can save sets that become inaccessible, in which case the sets displays as a question mark and can't be selected, equipped, or deleted. This happens with _only_ the default blizzard UI, with zero addons enabled.
  #### 1.2. How to Reproduce
          I'm not sure how to reproduce whatever caused the bug.
          I created a new set named "pvp", selected the crossed swords icon, clicked save.
          Now when I open equipment manager, I get the following error:
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/8125983/194706152-87f9a7ff-7825-46f3-a1f2-79d58b8805b2.png)
#### 2.1. Description
       I should be able to select, edit, or delete all equipment sets with the default UI.
  #### 2.2 Source Material
Full Error log as follows:
```
Message: Interface_Wrath\FrameXML\PaperDollFrame.lua:2302: attempt to index global 'dialog' (a nil value)
Time: Sat Oct  8 08:00:52 2022
Count: 1
Stack: Interface_Wrath\FrameXML\PaperDollFrame.lua:2302: attempt to index global 'dialog' (a nil value)
[string "@Interface_Wrath\FrameXML\PaperDollFrame.lua"]:2302: in function `GearSetButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = GearSetButton3 {
 0 = <userdata>
 id = 2
 text = GearSetButton3Name {
 }
 icon = GearSetButton3Icon {
 }
 Icon = GearSetButton3Icon {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = "attempt to index global 'dialog' (a nil value)"

```
See also: [Blizzard Forum Reports](https://us.forums.blizzard.com/en/wow/t/wotlk-classic-equipment-manager-broken/1358697)

**Comment by Evolvee** [comment] 2022-10-08 18:23
https://www.youtube.com/watch?v=MzOFsoeAh2Q

There is also this. Video is from prepatch but the bug is still the same with 100% reproduction rate, confirmed on live yesterday.

**Comment by thomas-parrish** [comment] 2022-10-13 21:10
Adding additional info from the wow forums comment here, for redundant visibility:

```Thanks for the solution of save not working, now I have a solution to the red ? issue:

There seems to be a discrepancy between how the Lua code in the UI understands the Lua API and what WoW is actually exporting. Lua code expects values between 0 and num_set-1, game is actually exporting numbers between 0 and 9. I suspect that what this means is if you delete anything other than the last set you end up w/ a question mark. I don’t know any way to recover those sets. You might be able to fix this by just creating new sets. What I ended up doing was killing all sets after the gap.

In my case I had 2 good sets, in slots 0 and 1, and 3 bad sets. Turns out the IDs were 0, 1, 7, 8, 9. So in my case I did:

/dump C_EquipmentSet.DeleteEquipmentSet(2)
(response) nil
/dump C_EquipmentSet.DeleteEquipmentSet(3)
(response) nil
…
/dump C_EquipmentSet.DeleteEquipmentSet(7)
(response something other than nil) (at this point one of the red ? disappeared)
/dump C_EquipmentSet.DeleteEquipmentSet(8)
(response something other than nil) (at this point another of the red ? disappeared)
/dump C_EquipmentSet.DeleteEquipmentSet(9)
(response something other than nil) (at this point last of the red ? disappeared)

Again, don’t know how to recover sets from this, but this can get you to a good state.

Also, I can not stress enough DO NOT DELETE SETS THAT ARE NOT THE LAST SET, it will bug up the manager.```

**Comment by AOSXX** [comment] 2022-10-14 08:45
You can try to create a new set that starts with the letter "z" like "zzzzzzz set". It unfroze my sets and I delted them.

**Comment by Evolvee** [comment] 2022-10-26 12:32
> https://www.youtube.com/watch?v=MzOFsoeAh2Q
> 
> There is also this. Video is from prepatch but the bug is still the same with 100% reproduction rate, confirmed on live yesterday.

this seems to be fixed now

**Closed** 2023-02-19 01:48 UTC
Labels: General, BUG, Fixed
