### ISSUE TITLE
[BUG] Inferno (Summon) not resetting cooldown on boss encounter end

### ISSUE THREAD

**Issue by nnyborg** [JamminL/wotlk-classic-bugs#486] opened 2022-10-21 07:47 UTC
1. Current Behavior
1.1. Description
Inferno (Summon) isn't properly resetting cooldown after boss encounter end in raid.

1.2. How to Reproduce
       1. Use Inferno on a boss
       2. Kill or wipe on boss
1.3 Source Material
https://us.forums.blizzard.com/en/wow/t/raid-system-adjustments-in-wrath-of-the-lich-king-classic/1307037/236

2. Expected Behavior
2.1. Description
According to the blue post i linked above, Inferno should not be excluded from resetting on boss encounter end.
The post clearly states that it is the full list of cooldowns exempt from resetting.

**Comment by watchyoursixx** [comment] 2022-10-21 22:28
duplicate of #358

**Closed by watchyoursixx** 2022-10-21 22:28 UTC
