### ISSUE TITLE
[BUG] Shadowmeld doesn't drop combat in arena/bgs (instanced pvp)

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#175] opened 2022-07-22 02:05 UTC
#### 1.1. Description
Shadowmeld doesn't drop combat when you use in during combat in instanced PVP (bgs/arena)
  #### 1.2. How to Reproduce
          
           1. Join Arena/bg
           2. Get in combat
           3. Press Shadowmeld
  #### 1.3  Source Material
https://gyazo.com/7f653cf1fd8a325be437deb0aeae5be8 (from beta)
#### 2.2 Source Material

https://www.youtube.com/watch?v=fLjTRifi6dE&ab_channel=GamingMoviez 2:56 you see he melds (bottom middle) and leaves combat

https://youtu.be/vFQl7JStwu4?t=304 

https://www.youtube.com/watch?v=sXd-AstxVrU&t=699s&ab_channel=WoWVideoArchive

**Comment by perpabc** [comment] 2022-08-04 19:49
Post on forum says this is fixed but it isn't as of today's build (4th August)

**Comment by uzbuzbuzb** [comment] 2022-08-08 01:48
it almost doesn't work at all in arena in fact. it will barely make you evade anything, even (most) projectile type spells like lava burst or deadly throw, let alone instant spells/abilities (kidney shot, blind, psychic scream etc)

**Comment by perpabc** [comment] 2022-08-10 21:25
Still isn't fixed as of new build

**Comment by JamminL** [comment] 2022-10-07 18:57
After the shadowmeld fix, it was noticable in instance PVP the ability wasn't working. After further testing it's related with group buffs. If you buffed or have been buffed by someone in PvP combat, your meld will not work: it won't drop combat or stop spells.

Case 1:
-  Rogue is in combat
 - Druid Lifeblooms rogue
 - Rogue shadowmelds
 - Shadowmeld fails to work

https://streamable.com/6oohf2

Case 2: 
- Rogue is in combat
- Druid buffs rogue with gift of the wild
- Rogue shadowmelds
- Shadowmeld fails to work

https://streamable.com/ibupit

Case 3
- Rogue is in combat
- Druid buffs rogue with lifebloom
- Druid Shadowmelds
- Shadowmeld fails to work

https://streamable.com/by7yg6

Case 4
- Rogue is in combat
- Druid buffs rogue with gift of the wild
- Druid Shadowmelds
- Shadowmeld fails to work

https://streamable.com/z4lab4

**Comment by NuptupTDOW** [comment] 2022-10-07 20:04
I have also had shadowmeld seem to cast, but not actually "do" anything in instanced dungeons as well. Could that be a similar cause?

**Comment by Oliaxz** [comment] 2022-10-10 21:11
Im not sure where this fall in the list of priority, but i feel like we've been really patient... racials should be considered core mechanic imo. Imagine human racial wasnt working atm.

**Comment by NuptupTDOW** [comment] 2022-10-12 19:32
If human Racial didn't work right now, the pvp crowd would be ddos'ing in rebellion. But, *shrug* night elfs are kind of used to the pain. I would love for it to work though. It also seems to happen in open world content as well. Like, I ran Old Kingdom normal last night and finished the dungeon, ran out, did the path from exit to summon stone, then tried to shadow meld to drop the two beetles that were chasing me and they just came around the corner with me targetted, while shadowmeld'ed, and walked right up and smacked me in the face. I was not under-leveled compared to them, I hadn't attacked, but it didn't matter. The racial just flat-out does not work about 75% of the time. I VERY rarely get it to work. If I knew it was this buggy, I likely would have went Draenei instead for the self-heal until Shmeld was fixed, then just race change when they add that.

**Comment by caccavale** [comment] 2022-10-12 20:02
Shadowmeld is--as far as I know--working correctly in instances: this is to say it works very poorly as a combat drop.
I'm relabeling this as a SomeChanges request.  It would help the case if we could find retail 3.3.5 footage of it working as a fast combat drop in instances.

**Comment by Oliaxz** [comment] 2022-10-12 20:14
> 

The not dropping combat in instanced is related to mob threat. 

The issue is with instanced pvp and bg. Players or their friends should be considered mobs.

Heres the patch note : 

[Patch 3.0.8](https://wowpedia.fandom.com/wiki/Patch_3.0.8) (2009-01-20): This ability will now properly restore threat when it is canceled. In addition, it will correctly remove a player from combat if it is active when that player is the last person left alive that the **creature hates**.

**Comment by caccavale** [comment] 2022-10-12 20:15
Arena and BGs are instances.  There seems to be a true to retail grace period of ~1s in these settings before combat is dropped.

**Comment by Oliaxz** [comment] 2022-10-12 20:17
> 

I dont understand why you think instance is more relevant than the creature/mob part. Players arent creature.

**Comment by caccavale** [comment] 2022-10-12 20:18
Combat works different in instances for both players and mobs is the clarification I am making.

**Comment by Oliaxz** [comment] 2022-10-12 20:22
> Combat works different in instances for both players and mobs is the clarification I am making.

Have you seen the above streamable? There is no delay on combat drop. It just doesnt drop combat ever.

**Comment by caccavale** [comment] 2022-10-12 20:24
> Similar to batched Feign Death from classic, friendly auras can keep the player in combat longer than that 1 second and sometimes indefinitely, thus making the meld useless.

Yes.

**Comment by Oliaxz** [comment] 2022-10-12 20:33
> > Similar to batched Feign Death from classic, friendly auras can keep the player in combat longer than that 1 second and sometimes indefinitely, thus making the meld useless.
> 
> Yes.

Well then is what you're describing considered a bug in classic? 

Is this whats causing shadowmeld to behave like it is? 

Either way its a bit much to retag this has some change imo.

**Comment by caccavale** [comment] 2022-10-12 20:37
Its not a bug though-- this is how it behaved.  If you believe otherwise please source video of near instant combat drops from meld on 3.3.5 retail.  You will find many successful drops after around 600ms -> 1.2s when the melding character does not have any aura's refreshed after the meld; that is consistent with classic as well.

**Comment by caccavale** [comment] 2022-10-12 20:40
Jammin's corrected me-- should be around 400ms unless you have an aura refreshed by a friendly before then, in which case it can be 1-2s or indefnitely.

**Comment by Oliaxz** [comment] 2022-10-12 21:50
This video from wotlk shows an instant combat drop in BG at 5:10.
https://youtu.be/EqLPKtBlOmw?t=310

This also seem to work in classic when i tested it in skirmishes, but my partner must be out of combat for it to work.

I have also done skirmishes where i waited for my partner to engage, then used faerie fire on an enemy target from prowl, and then used shadowmeld instantly after. Shadowmeld did not make me drop combat instantly or after 1-2s, even when i had zero buff or aura refreshed/applied. You will only drop combat once the normal 5-6s combat timer is over. 

To me this mean that shadowmeld is using party combat/threat status rather than aura refresh. Which is to say that if ur teamate is in combat, you will never drop combat by using shadowmeld. And it may actually reset your combat timer if you use it lets say 3s after casting nothing. This is a pve behavior rather than aura refresh issue.

**Comment by Unluckycat8** [comment] 2022-10-13 17:35
Im really annoyed and dissapointed that such a basic stuff as racial doesnt work. Im starting to think that it won't be repaired ever since its almost 3 months of this post. Such a gamechanging thing. Please make it work, many ppl will love you.

**Comment by NuptupTDOW** [comment] 2022-10-13 19:39
I don't mean to sound like the broken record, but genuinely, yes. This not working like it did 12 years ago is a pretty big letdown. I don't have any concrete video evidence of someone doing an instant combat drop in dungeons or open world, since I've been grinding to hit max level, but I will certainly be hunting for it when I get there. But, I very clearly remember having specific dungeon pulls that relied on me running through as a tank, pulling a huge group of mobs to aoe down, and if I messed up my pathing it would screw it all up, so I would just shadow meld, drop all aggro, then do the entire pull in reverse back to the group. 

Maybe it's weird interactions with having a pet this time since I'm doing stuff as Unholy tank for fun but in original wrath I was frost and later blood, so maybe the existence of having a pet is causing it to not work pretty much at all, even if pet is on passive during pull and dismissed after the shadow meld. But, in dungeons and in open-world pve solo questing, I get about 25% success rate on shadow melds, and it's just the definition of disappointment every single time. Run away from mobs VERY far, pop shadow meld, then dismiss pet, then just watch as they still have me targeted, and take 6-7 seconds to get to me then bash my face in.

**Comment by JamminL** [comment] 2022-10-16 23:15
#476 closing this linking back to the new post.

**Closed by JamminL** 2022-10-16 23:15 UTC
Labels: #SomeChanges Suggestion
