### ISSUE TITLE
[BUG] Volley not doing damage on first tick

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#208] opened 2022-07-25 12:16 UTC
#### 1.1. Description
you shoot volley and it doesn't do any damage on the first channeling tick.
  #### 1.2. How to Reproduce
use volley on something
  #### 1.3  Source Material
https://www.twitch.tv/videos/1542196065?t=1h24m23s
#### 2.1. Description
It should do damage on the first channeling tick already
  #### 2.2 Source Material
https://youtu.be/vxUeCb3sfgc?t=125

**Comment by JamminL** [comment] 2022-07-25 12:23
Duplicate of #111

**Closed** 2022-07-25 12:23 UTC
Labels: duplicate, Pending Approval
