### ISSUE TITLE
[BUG] [UI] Equip Manager: Alt <> hover over interaction => should show item menu  

### ISSUE THREAD

**Issue by dawidcxx** [JamminL/wotlk-classic-bugs#501] opened 2022-10-25 14:10 UTC
### 1. Current Behavior

When inspecting your own gear & having equip manager enabled, pressing ALT while hovering over an item doesn't show the item selection menu.

#### 1.2. How to Reproduce

           1. Enable equip manager feature (ESC > interface > Features)
           2. Open up your gear inspection menu (Character Info at the middle bottom) 
           3. Hovering your cursor over an item hold ALT
           4. Nothing happens

### 2. Expected Behavior
 On step 4 your item selection menu should be automatically visible. Like so 
 
![image](https://user-images.githubusercontent.com/7695966/197796260-877bc21a-0d30-45bd-8594-3d93d336d5c2.png)

**Comment by CharWS** [comment] 2022-10-25 14:44
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/172

**Closed by CharWS** 2022-10-25 14:44 UTC
Labels: Pending Approval
