### ISSUE TITLE
[BUG] Warlock pet - Seduction 13 seconds

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#227] opened 2022-07-29 10:17 UTC
#### 1.1. Description
Seduction from succubus and incubus last 13 seconds vs players
  #### 1.2. How to Reproduce
Press seduction on a player
  #### 1.3  Source Material
https://gyazo.com/2deaec4debc0ae6495bc3ca238d4a24f
#### 2.1. Description
Seduce should last 10 seconds, not 13 seconds
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment] 2022-07-29 12:22
Duplicate of #80

**Closed by JamminL** 2022-07-29 12:23 UTC
Labels: duplicate
