### ISSUE TITLE
[BUG] warrior t10 4 set proc buff override

### ISSUE THREAD

**Issue by BerserkerGaruk** [JamminL/wotlk-classic-bugs#784] opened 2023-10-30 08:38 UTC
#### 1.1. Description
Bloodthirst, whirlwind, and heoric strike have a chance to trigger a 0 cast slam. The warrior t10 has a 20% chance to make this trigger a double use at lower gcd. 

If you proc an additional bloodsurge through heroic strike, bloodthirst, or whirlwind while your at 1 or 2 stacks of the 10 second buff, the 'better' buff is replaced by the 5 second buff.
  #### 1.2. How to Reproduce
Perform your normal rotation until you get a bloodsurge proc. Do not use the proc until it gets replaced by the 5 second proc. If you use one stack and then hit with a heroic strike that triggers bloodsurge, that buff can override single stack of the tier even if the tiers proc would have a longer duration.
#### 2.1. Description
The 10 second slam proc should be flagged as a better buff and not be overidden by the normal proc.

**Comment by BonePorpoise** [comment] 2023-11-01 16:38
While attempting to corroborate this post with log/video evidence, I found another way in which the 4 piece t10 proc can be overwritten by a normal bloodsurge proc. First here is the proc being overwritten as OP described:
[WCL Link](https://classic.warcraftlogs.com/reports/mqJ9Hf1ahbvgYZ3L#fight=last&source=14&view=events&type=auras&ability=46916&pins=0%24Off%24%23244F4B%24expression%24ability.name%3D%22Slam%22%20OR%20ability.name%3D%22Sunder%20Armor%22)
![SlamOverwrite#1](https://github.com/JamminL/wotlk-classic-bugs/assets/149602175/249d160c-2c6d-4eca-bd96-a9e12efc9e63)

https://github.com/JamminL/wotlk-classic-bugs/assets/149602175/385677b9-1a3f-4764-af62-fd96986c99e4

The second way in which the 4pc slam buff can be overwritten is when the duration of the buff falls below 5 seconds. Even when you still have 2 stacks of the 4pc slam buff remaining, the buff can be overwritten by a non-4pc bloodsurge proc, resulting in the player losing a stack of slam as well as the GCD reduction from the buff:
[WCL Link](https://classic.warcraftlogs.com/reports/rWbZPghfq6KGBdRV#fight=last&type=auras&source=7&view=events&ability=46916)
![SlamOverwrite#2](https://github.com/JamminL/wotlk-classic-bugs/assets/149602175/f434dc6b-ec61-4a33-aeb0-330bbaba8c47)

https://github.com/JamminL/wotlk-classic-bugs/assets/149602175/097af204-d47c-421e-9c57-3c4bc6571121

**Comment by JamminL** [comment] 2023-11-02 20:01
Not a bug, unfortunately this behavior was also present in 3.3.5a, I have to close it but I suggest opening a #somechanges suggestion instead

**Closed by JamminL** 2023-11-02 20:01 UTC
Labels: Warrior, Not a Bug
