### ISSUE TITLE
 [BUG] Omen of Clarity not procing from instant cast spells

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#66] opened 2022-06-27 22:45 UTC
#### 1.1. Description
Currently, Omen procs consistently from melee hits in all forms and hard casted spells at around a 6% proc rate.  It does not seem to proc from any instant spell casts including healing, damage, and buffs.  The 3.0.2 patch notes include _"*Omen of Clarity (Restoration): Now a passive spell. Now also works for spells (healing and damage)."_
  #### 1.2. How to Reproduce
          1. hit stuff for a while, omen will proc
          2. repeatedly cast instant cast spells on self / others, omen will not proc
  #### 1.3  Source Material
[Hour long log of omen on melee](https://classic.warcraftlogs.com/reports/KVBcwQYgZtC837JT/)

#### 2.1. Description
Omen of Clarity should have a chance to proc on all spells including instant casts.  Procs from spellcasts should trigger a 10s iCD on additional procs _from casts;_ during this iCD, melee procs should still occur.  The emergent behavior should also be that multitarget spells have a chance to proc omen per target hit.  This was apparently nerfed for Hurricane in 3.0.3 _"* Druid: Omen of Clarity now has a reduced chance to be triggered by Hurricane,"_ but I'm unsure how that nerf was applied and assume it did not apply to other AoE or multi-target since it was so specifically worded (e.g. Wild Growth).
  #### 2.2 Source Material
[Proc on Gift of the Wild](https://youtu.be/KFMPEECCAP0?t=41)
[EJ thread mentioning multiprocs](https://web.archive.org/web/20100731043147/http://elitistjerks.com:80/f47/t66856-druid_balance_pve_updated_3_3_5_a/)
![image](https://user-images.githubusercontent.com/6198074/176051264-cf34a865-2ccd-435c-8536-f6e81bcf5a6b.png)
![image](https://user-images.githubusercontent.com/6198074/176051451-01337924-ba1f-4620-b702-0dea73e88f59.png)
![image](https://user-images.githubusercontent.com/6198074/176051461-5a120381-96b8-45b3-b2c7-44ea344c2cdf.png)

[Wowhead comments mention crafts (I know, not great)](https://www.wowhead.com/wotlk/spell=16864/omen-of-clarity#comments)

**Comment by MonomitoWoW** [comment] 2022-07-07 22:11
We've done some additional testing on Omen of Clarity procs and have noticed the following behavior:

1. Melee procs are using ~3.5 PPM (expected).
2. Non-instant spell casts appear to proc using ~1.75 PPM, varying by base cast time.

This is somewhat expected behavior based on a [blue post from the beginning of WotLK](https://www.mmo-champion.com/threads/611019-Blue-Posts-on-Agility-base-crit-OOC-change-Haste-and-Range-Bug):
> The 10 second cooldown has been removed, the procs per minute has been raised from 2 to 3.5, and melee abilities no longer trigger it. Spell interaction with Omen of Clarity remains relatively unchanged, with its hidden chance to trigger off spells reduced by half (and rolling the dice about 2x as often).

If PPM varying by base cast time is the intended functionality, then the game is currently mishandling instant casts. Theoretically this would lead to a divide by 0 in the proc chance calculation, but it appears to instead be using some very low minimum chance to proc.

**Data**
1. Cat White Hits (0 Haste on character): https://classic.warcraftlogs.com/reports/vh3kfNbt9pqVz7KC/#fight=last&type=auras&source=8
106 Procs in 31.404 minutes = 3.375PPM (Expected is 3.5PPM)

2. Bear White Hits (0 Haste on character):
https://classic.warcraftlogs.com/reports/cpAG3WVrNaDqxhC9/#fight=2&type=auras&source=8
111 Procs in 30.787 minutes = 3.605PPM (Expected is 3.5PPM)

3. Starfire Hits (121 Haste Rating/7% Haste on character):
https://classic.warcraftlogs.com/reports/6FVcQZDLzpwmdMnN/#type=auras&boss=-3&difficulty=0&source=7&start=1375340&end=3345422
55 Procs in 568 Hits for 9.68% Proc Chance (1.75 PPM would give expected 10.2% Proc Chance)

4. Wrath Hits (121 Haste Rating/7% Haste on character):
https://classic.warcraftlogs.com/reports/4jGhbrpXg867cQtK/#boss=-3&difficulty=0&type=auras&source=6
52 Procs in 837 Hits for 6.21% Proc Chance (1.75 PPM would give expected 5.8% Proc Chance)

5. Mark of the Wild used to test instants:
https://classic.warcraftlogs.com/reports/gCkmMXVjFfczdwaT/#fight=3&type=auras&source=10
1 Proc in 267 Casts

6. Gift of the Wild used to test instants:
https://classic.warcraftlogs.com/reports/MLQAq9bKcHfJnamk/#boss=-3&difficulty=0&type=auras&source=1
1 Proc in 175 Casts

**Expected Behavior**
Given the new info the expected behavior would be:
- Instant Cast Spells use a PPM according to the GCD (1.5sec).
- Omen of Clarity has no internal cooldown on spells (current behavior)

**Comment by Aggrend** [comment] 2022-07-12 17:01
This is Not A Bug. We found that this did occasionally proc on instant cast spells including things like Gift of the Wild, but it was rare and this is intended. Our designer provided this explanation of how this is set up and that it matches his expectations and intent now (and when he wrote the script in 2008). Here's what he had to say:


So, Omen of  Clarity has a proc script on it for two purposes: 1) to prevent procs from things that shouldn't trigger it, like tradeskills; 2) to reduce the chance to proc from spells that would otherwise trigger it too often. It also can't proc if you have the Aura of Despair while fighting General Vezax in Ulduar.

Its core data is to proc 3.5 times per minute. That results in the 8.75% chance for instants and spells with under 1.5 second cast time. (3.5/(60/1.5)=0.0875).

It also reduces the chance to proc for Wild Growth and Typhoon because they hit multiple targets, so they have a 75% chance the proc will fail in script.

It reduces the chance Hurricane will proc because it has multiple ticks of damage. Each damage event has a 7/9 (77.7%) chance it will fail in script.

It checks for spells which are instant after that, and massively reduces their chance by 92.4%. So Moonfire and Gift of the Wild have a huge penalty. This number was picked by feel.

Finally, all other spells have a 33% chance to fail in script because they are spells. It just plain procs a lot more for Bears and Cats, by design.

So, all the spells you listed are supposed to have a much smaller chance to proc.

In Burning Crusade, none of this scripting existed, but it only worked for melee attacks. It was 2x per minute with a 10 second cooldown. So, it got a lot stronger for melee in LK, and LK started allowing spells to trigger it, at reduced chances.

**Comment by caccavale** [comment] 2022-07-12 17:05
Thank you for this write up!  Closing the ticket as NAB.

**Comment by JamminL** [comment] 2022-07-18 17:41
> This is Not A Bug. We found that this did occasionally proc on instant cast spells including things like Gift of the Wild, but it was rare and this is intended. Our designer provided this explanation of how this is set up and that it matches his expectations and intent now (and when he wrote the script in 2008). Here's what he had to say:
> 
> So, Omen of Clarity has a proc script on it for two purposes: 1) to prevent procs from things that shouldn't trigger it, like tradeskills; 2) to reduce the chance to proc from spells that would otherwise trigger it too often. It also can't proc if you have the Aura of Despair while fighting General Vezax in Ulduar.
> 
> Its core data is to proc 3.5 times per minute. That results in the 8.75% chance for instants and spells with under 1.5 second cast time. (3.5/(60/1.5)=0.0875).
> 
> It also reduces the chance to proc for Wild Growth and Typhoon because they hit multiple targets, so they have a 75% chance the proc will fail in script.
> 
> It reduces the chance Hurricane will proc because it has multiple ticks of damage. Each damage event has a 7/9 (77.7%) chance it will fail in script.
> 
> It checks for spells which are instant after that, and massively reduces their chance by 92.4%. So Moonfire and Gift of the Wild have a huge penalty. This number was picked by feel.
> 
> Finally, all other spells have a 33% chance to fail in script because they are spells. It just plain procs a lot more for Bears and Cats, by design.
> 
> So, all the spells you listed are supposed to have a much smaller chance to proc.
> 
> In Burning Crusade, none of this scripting existed, but it only worked for melee attacks. It was 2x per minute with a 10 second cooldown. So, it got a lot stronger for melee in LK, and LK started allowing spells to trigger it, at reduced chances.

Based on this post, Gift of the Wild should have **at best** a **15%** chance to proc **1** clearcasting in a **raid** scenario:
`0.875(base chance) * 0.076(instant penalty) ~= 0.665 %`
`1 - (1 - 0.00665)^25 = 0.1536355703 ~= 15.36 %`

And this is without taking into account the alledged penalty for multi-target spells such as wildgrowth mentioned in the post (since it wasnt explicitly mentioned it applied to GOTW).

We looked at wc logs from 3.3.5a and it seems in a raid scenario, Gift of the Wild procs **100%** of the time (25 targets), sometimes even proccing 2 or 3 - which completely debunks the 15% chance and beta behavior.

I've sent an example of a full log through proper channels but I'll keep some examples here:

> [00:06:45.743] [Druid#Shinjiru] casts [Gift of the Wild#spell=48470]
> [00:06:45.752] [Mage#Greatmerlin]'s [Gift of the Wild#spell=48470] is refreshed by [Druid#Shinjiru]
> [00:06:46.115] [Druid#Shinjiru] gains [Clearcasting#spell=16870] from [Druid#Shinjiru]
> 
> [00:12:04.228] [Druid#Shinjiru] casts [Gift of the Wild#spell=48470]
> [00:12:04.259] [Mage#Greatmerlin]'s [Gift of the Wild#spell=48470] is refreshed by [Druid#Shinjiru]
> [00:12:04.776] [Druid#Shinjiru] gains [Clearcasting#spell=16870] from [Druid#Shinjiru]
> 
> [00:15:47.132] [Druid#Shinjiru] casts [Gift of the Wild#spell=48470]
> [00:15:47.278] [Mage#Greatmerlin] gains [Gift of the Wild#spell=48470] from [Druid#Shinjiru]
> [00:15:47.685] [Druid#Shinjiru] gains [Clearcasting#spell=16870] from [Druid#Shinjiru]
> 
> [00:39:40.416] [Druid#Shinjiru] casts [Gift of the Wild#spell=48470]
> [00:39:40.428] [Mage#Nieeru] gains [Gift of the Wild#spell=48470] from [Druid#Shinjiru]
> [00:39:40.821] [Druid#Shinjiru] gains [Clearcasting#spell=16870] from [Druid#Shinjiru]
> [00:39:40.821] [Druid#Shinjiru]'s [Clearcasting#spell=16870] is refreshed by [Druid#Shinjiru]

----------

>  00:09:02.267] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [00:09:02.550] [Druid#Freestyler] gains [Gift of the Wild#spell=48470] from [Druid#Caer]
> [00:09:02.741] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> [00:09:02.741] [Druid#Caer]'s [Clearcasting#spell=16870] is refreshed by [Druid#Caer]
> 
> [00:36:26.857] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [00:36:26.988] [Druid#Freestyler]'s [Gift of the Wild#spell=48470] is refreshed by [Druid#Caer]
> [00:36:27.378] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> 
> [00:59:40.304] [Druid#Freestyler] casts [Gift of the Wild#spell=48470]
> [00:59:40.321] [Priest#Charovna] gains [Gift of the Wild#spell=48470] from [Druid#Freestyler]
> [00:59:40.742] [Druid#Freestyler] gains [Clearcasting#spell=16870] from [Druid#Freestyler]
> 
> [00:59:40.992] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [00:59:41.248] [Druid#Freestyler]'s [Gift of the Wild#spell=48470] is refreshed by [Druid#Caer]
> [00:59:41.517] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> [00:59:41.517] [Druid#Caer]'s [Clearcasting#spell=16870] is refreshed by [Druid#Caer]
> [00:59:41.523] [Druid#Caer]'s [Clearcasting#spell=16870] is refreshed by [Druid#Caer]
> 
> [01:33:52.154] [Druid#Riddly] casts [Gift of the Wild#spell=48470]
> [01:33:52.377] [Priest#Keyena] gains [Gift of the Wild#spell=48470] from [Druid#Riddly]
> [01:33:52.661] [Druid#Riddly] gains [Clearcasting#spell=16870] from [Druid#Riddly]
> 
> [01:40:48.018] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [01:40:48.145] [Shaman#Vexsanity] gains [Gift of the Wild#spell=48470] from [Druid#Caer]
> [01:40:48.571] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> 
> 
> [02:12:35.094] [Druid#Freestyler] casts [Gift of the Wild#spell=48470]
> [02:12:35.511] [pet#Phuudhun, $2409] gains [Gift of the Wild#spell=48470] from [Druid#Freestyler]
> [02:12:35.832] [Druid#Freestyler] gains [Clearcasting#spell=16870] from [Druid#Freestyler]
> 
> 
> [02:29:23.788] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [02:29:24.322] [Valithria Dreamwalker#npc=36789, $2857] gains [Gift of the Wild#spell=48470] from [Druid#Caer]
> [02:29:24.553] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> [02:29:24.556] [Druid#Caer]'s [Clearcasting#spell=16870] is refreshed by [Druid#Caer]
> 
> [02:39:59.950] [Druid#Caer] casts [Gift of the Wild#spell=48470]
> [02:39:59.950] [Warlock#Xeria] gains [Gift of the Wild#spell=48470] from [Druid#Caer]
> [02:40:00.368] [Druid#Caer] gains [Clearcasting#spell=16870] from [Druid#Caer]
> [02:40:00.370] [Druid#Caer]'s [Clearcasting#spell=16870] is refreshed by [Druid#Caer]

**Comment by JamminL** [comment] 2022-07-18 17:42
Also adding #138 here as reference (possibly same problem)

**Comment by amarathTESTER** [comment] 2022-07-29 12:37
So i reviewed videos ... i know imperfect at best.  I actually went though many patches of videos on yt (as dates are easily noted). 

https://www.youtube.com/watch?v=YF7nJ0JiYo0
3.3.5 While there is some spell casting with it its a proc every 18s. even if you toss them out its still in the 20s range per second to proc. Which is a far cry from like ~200 st instas or ~600 Wg applications. 
Another video from same night but diff boss. https://www.youtube.com/watch?v=SMdWg-Ksc40

3.3.5a dungeon video from day before prepatch https://www.youtube.com/watch?v=Ow5DR16dWYk 
Basically clear casting from instas is every ~20s. Im not counting the actual ppm here, but its way more than suppose script and beta from last week. Like a factor of 10 more.

Hx of it as well to see if it changed (it did not singfically change in rate of procing for at least druid hots.)

3.3.2 
one of these is super lucky but only by a factor of 2.  
https://www.youtube.com/watch?v=aQqksfpSwA8
https://www.youtube.com/watch?v=3K_8KvS43sM

3.2.2 
https://www.youtube.com/watch?v=P5-MZ3NyqU0

3.1.3 
https://www.youtube.com/watch?v=P5-MZ3NyqU0

3.0.0 (original beta for wrath)
https://youtu.be/7l050W7mLSA?t=113

More, but i think the point is made.

**Comment by JamminL** [comment] 2022-08-24 17:45
Fixed as of build 3.4.0.45264

**Closed by JamminL** 2022-08-24 17:45 UTC
Labels: Druid, BUG, Fixed

**Comment by fearkite** [comment] 2022-08-25 03:43
Just for clarification; is this suppose to fix Faerie Fire (Feral) not proccing Omen as well? If so, it hasn't been fixed for FF + Omen. :(

**Comment by Tadiaki** [comment] 2022-08-25 11:47
So now we have reached some kind of "middle ground" between how Omen of Clarity
worked back in the original WotLK game and how it works in the latest build 3.4.0.45264

Thank you first and foremost, for looking into Omen of Clarity and listening to bug reports, community etc.


Back in the original WotLK days, it used to proc from **basically anything** (video source below with original WotLK video).

The current state of Omen of Clarity is an inferior version to its original counterpart, and I'm wondering if that class balance nerf is intended or we are still homing in on making it balanced as it used to be?

For PvE purposes the GoTW proc chance that now seems to work, has mostly restored the possbility to playstyle a druid with flowershifting (although there are niche scenarios with barkskin, FF etc. being used, that does still not work now). So only a minor nerf at this point with the latest build.

But for PvP purposes, not getting these OOC procs from certain instant cast spells is a more considerable balance nerf.

**Source**:
https://www.youtube.com/watch?v=jxAiinyV-PI&ab_channel=arenaimbapvp

At:
0m 19s the Druid uses Survival Instincts and Feral Charge - Bear (since no GCD they are cast almost at the same time) and as you can see, either of the 2 spells procs OOC.

0m 55s - the Druid casts instant Cyclone on the warrior and it procs OOC

1m 4s - the Druid casts instant Cyclone on his focus target and it procs OOC

1m 34s - the Druid casts instant Cyclone on his focus target and it procs OOC

1m 56s - Melee proc

1m 59s - Again so shortly after - looks like a mangle proc, but probably just melee?

2m 02s - Again already - from Instant cast Cyclone (overwrites the other buff, you can see the duration goes up to max again).

Some procs occur between these time intervals, but many are the same, so I'm just going to mention a few specifik ones.

2m 57s - Druid casts instant Entangling Roots on Warrior - procs OOC

5m 47s - Druid uses Trinket and Casts Faerie Fire (no attacks or anything else it looks like) and OOC procs.

6m 03s - Druid casts **Abolish Poison** and it procs OOC

7m 21s - Another instant Cyclone at target for a OOC proc.

Using all sorts of instant casts, such as from Predatory Strikes or using Survival Instincts, Abolish Poison or Natures Grasp, Barkskin, Innervate, Faerie Fire, Rejuvenation, Feral Charge, etc. they all had a chance to proc OOC, even those not on GCD.


Anyway, there are countless of old videos on youtube, although 480p isn't exactly pleasing to the eye, it still proves how the original OOC worked.
Regardless of how it was supposed to work back then, it did in fact work in a certain way, and the current version is inferior to that.

So what is the goal with OOC? :-)

**Comment by JamminL** [comment] 2022-08-25 12:47
> So now we have reached some kind of "middle ground" between how Omen of Clarity worked back in the original WotLK game and how it works in the latest build 3.4.0.45264
> 
> Thank you first and foremost, for looking into Omen of Clarity and listening to bug reports, community etc.
> 
> Back in the original WotLK days, it used to proc from **basically anything** (video source below with original WotLK video).
> 
> The current state of Omen of Clarity is an inferior version to its original counterpart, and I'm wondering if that class balance nerf is intended or we are still homing in on making it balanced as it used to be?
> 
> For PvE purposes the GoTW proc chance that now seems to work, has mostly restored the possbility to playstyle a druid with flowershifting (although there are niche scenarios with barkskin, FF, Survival Instincts etc. being used, that does still not work now). So only a minor nerf at this point with the latest build.
> 
> But for PvP purposes, not getting these OOC procs from certain instant cast spells is a more considerable balance nerf.
> 
> **Source**: https://www.youtube.com/watch?v=jxAiinyV-PI&ab_channel=arenaimbapvp
> 
> At: 0m 19s the Druid uses Survival Instincts and Feral Charge - Bear (since no GCD they are cast almost at the same time) and as you can see, either of the 2 spells procs OOC.
> 
> 0m 55s - the Druid casts instant Cyclone on the warrior and it procs OOC
> 
> 1m 4s - the Druid casts instant Cyclone on his focus target and it procs OOC
> 
> 1m 34s - the Druid casts instant Cyclone on his focus target and it procs OOC
> 
> 1m 56s - Melee proc
> 
> 1m 59s - Again so shortly after - looks like a mangle proc, but probably just melee?
> 
> 2m 02s - Again already - from Instant cast Cyclone (overwrites the other buff, you can see the duration goes up to max again).
> 
> Some procs occur between these time intervals, but many are the same, so I'm just going to mention a few specific ones.
> 
> 2m 57s - Druid casts instant Entangling Roots on Warrior - procs OOC
> 
> 5m 47s - Druid uses Trinket and Casts Faerie Fire (no attacks or anything else it looks like) and OOC procs.
> 
> 6m 03s - Druid casts **Abolish Poison** and it procs OOC
> 
> 7m 21s - Another instant Cyclone at target for a OOC proc.
> 
> Using all sorts of instant casts, such as from Predatory Strikes or using Survival Instincts, Abolish Poison or Natures Grasp, Barkskin, Innervate, Faerie Fire, Rejuvenation, Feral Charge, etc. they all had a chance to proc OOC, even those not on GCD.
> 
> Anyway, there are countless of old videos on youtube, although 480p isn't exactly pleasing to the eye, it still proves how the original OOC worked. Regardless of how it was supposed to work back then, it did in fact work in a certain way, and the current version is inferior to that.
> 
> So what is the goal with OOC? :-)

First of all thanks for providing some references! To add to this though, according to these videos: https://github.com/JamminL/wotlk-classic-bugs/issues/138#issuecomment-1183824708 proc chance among different patches from PS instant casts were around 60% which is consistent with current BETA, do you have any evidence to suggest the contrary (regarding PS instants) ?

**Comment by Freedye** [comment] 2023-03-03 11:42
Why isn't Faerie Fire (Feral) not procing OoC?
OoC's tooltip is: "Each of the Druid's damage, healing spells and auto attacks has a chance of causing the caster to enter a Clearcasting state. The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage, healing spell or offensive ability by 100%.". 
Since Faerie Fire (Feral) is spell that deals AP * 0.108 + 1 in nature damage, shouldn't that also be able to proc it?
