### ISSUE TITLE
[#SomeChanges Suggestion]Dancing Rune Weapon first hit scaling

### ISSUE THREAD

**Issue by MHMabrito** [JamminL/wotlk-classic-bugs#651] opened 2023-04-07 13:13 UTC
1.    Current Behavior

If you spawn Dancing Rune Weapon on a target you’re currently engaged with, its first auto attack will do significantly less damage than expected.

1.1.    Description

The damage of your Dancing Rune Weapon auto attacks are based on a snapshot of your stats. However, if the Dancing Rune Weapon is cast while engaged with a target, the first auto attack seems unaffected by this. 

1.2.    How to Reproduce

1.    Have a Death Knight cast Dancing Rune Weapon on a target while being out of combat/away from the target.
2.    Go inside your log or damage meter and take a look at the damage from the first auto attack of your Dancing Rune Weapon.
3.    Have a Death Knight cast Dancing Rune Weapon while being in combat and auto-attacking the target.
4.    Go inside your log or damage meter and take a look at the damage from the first auto attack of your Dancing Rune Weapon.
5.    Notice that the first auto attack of the Dancing Rune Weapon you cast while engaged with the target has done significantly less damage.

1.3.    Source Material
 https://youtu.be/9MQaifIn_k4?t=30

2.    Expected behavior.

Dancing Rune Weapon’s auto attacks should always hit for their fully scaled damage, regardless of the situation.

**Comment by CharWS** [comment] 2023-04-07 16:58
Duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/194

**Closed by CharWS** 2023-04-07 16:58 UTC
Labels: #SomeChanges Suggestion
