### ISSUE TITLE
[BUG] Unholy DK Gargoyle Summon Positioning Incorrect 

### ISSUE THREAD

**Issue by Bakurersu** [JamminL/wotlk-classic-bugs#386] opened 2022-09-03 02:15 UTC
#### 1.1. Description
As of build 45327, the position at which ebon gargoyle is summoned when the spell is cast has been changed. Currently when summoned, it spawns directly above the target, regardless of which direction the player is facing. This means that the gargoyle always does at least 1 melee hit before beginning to cast. Summoning positioning of the gargoyle was correct in builds prior to 45327
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Initiate combat with a hostile unit
           2. Gain enough runic power to summon gargoyle
           3. Face character in any direction, including away from the enemy 
           4. Gargoyle will always spawn directly above enemy
  #### 1.3  Source Material
https://www.youtube.com/watch?v=J_kbfpHxYyo (Build 45425 on live pre-patch)
https://clips.twitch.tv/ExuberantPlausibleFalconMingLee-sCmEqxnLrxkaunB- (Shows how summon gargoyle worked during raid testing on beta prior to build 45327)
#### 2.1. Description
Gargoyle should spawn in front of the player in the direction the player is facing, regardless of enemy positioning (assuming it won't spawn out of bounds)
  #### 2.2 Source Material
{Video, Posts, etc..}
https://youtu.be/teIODQeVjOI?t=381 (6:22)
https://youtu.be/BYK6OkFwbv8?t=102 (1:42, 3:42, multiple other times)
https://www.youtube.com/watch?v=FzVxnsXxChs (1:24 and multiple other times)
https://www.youtube.com/watch?v=ss2tcV4AgWE (0:20, 2:46, 5:28, multiple other times)

**Comment by yurpcraft** [comment] 2022-09-04 01:30
Is this not a duplicate of #200 ?

**Comment by Bakurersu** [comment] 2022-09-04 07:59
I believe it is a new issue that has been caused by the fix implemented for #200. I have not been able to replicate the behaviour described in #200 during my testing for this issue

**Comment by Misery321** [comment] 2022-09-08 14:31
According to the old videos you linked it should spawn to the left of the caster.

**Comment by Inezi** [comment] 2022-09-09 01:11
look at this
https://classic.warcraftlogs.com/reports/JnRY8LxGzPvHpXcB#fight=3&type=damage-taken&hostility=1&view=events&target=61

**Comment by Jordanmainz** [comment] 2022-09-11 10:00
![42164D4E-0135-4AEF-9423-729FE19AB7D4](https://user-images.githubusercontent.com/7857068/189521749-cfdbfd39-20db-4e45-bc28-db7489594218.jpeg)

24 melees on gruul

**Closed** 2023-02-14 03:57 UTC
Labels: Death Knight, BUG, Fixed
