### ISSUE TITLE
[BUG] Arms Warrior Talent 'Taste for blood' does not work

### ISSUE THREAD

**Issue by Fedxlol** [JamminL/wotlk-classic-bugs#191] opened 2022-07-24 10:14 UTC
#### 1.1. Description
The Arms Warrior Talent called Taste for blood which is supposed to give the use of Overpower from Rend is not working. You get the proc but unless the target has dodged an ability you can't press your Overpower ability, even though it lights up. It should work both on dodges like it has done in Vanilla classic / TBC classic but should now also proc from Rend.
  #### 1.2. How to Reproduce
                    1. Spec into taste for blood
                    2. Press rend on a target
                    3. Wait for taste for blood proc, see your overpower light up. But when you press it nothing happens.
                     
#### 2.1. Description
 The Arms Warrior Talent called Taste for blood which is supposed to give the use of Overpower from Rend is not working. You get the proc but unless the target has dodged an ability you can't press your Overpower ability, even though it lights up. It should work both on dodges like it has done in Vanilla classic / TBC classic but should now also proc from Rend.

  #### 2.2 Source Material
Talent description should be more than enough.

**Comment by JamminL** [comment] 2022-07-24 14:19
duplicate of #34

**Closed by JamminL** 2022-07-24 14:19 UTC
Labels: duplicate
