### ISSUE TITLE
[BUG] Warrior Disarm

### ISSUE THREAD

**Issue by Moki182** [JamminL/wotlk-classic-bugs#604] opened 2023-02-01 12:37 UTC
Hi

The Warrior ablity "Disarm" is bugged.
When I get disarm from an enemy warrior I cannot switch to one handed and shield.
Therefore I cannot use any Shield required abilites like Shield Wall, Shield Block, Spell Reflection, Shield Bash and Shield Slam.

This is how it worked back in the day:
https://youtu.be/wmAGsDHR8j8?t=401  6:41

This is how it should work:
Disarm should only take away the Main Hand and Ranged Weapons "if they are equipped" -- this is important.
When only one of them is equipped then it should take that away only. -- and you can re-equip the other one to use it.
When no Main Hand and Ranged are equipped then the Disarm cannot be performed.

I know that in Classic Wrath Season 5 warrios could use shield wall when rogues dismantled their 2handed,
and I know this is the easy fix for it but this is worse.... In a way,,, now warriors has dismantle aswell.

**Comment by JamminL** [comment] 2023-02-01 12:38
Duplicate of #603

**Closed by JamminL** 2023-02-01 12:38 UTC
Labels: Pending Approval
