### ISSUE TITLE
[BUG] Omen of clarity doesn't have an increased chance to proc from spells that have their cast time reduced

### ISSUE THREAD

**Issue by peterderpirat** [JamminL/wotlk-classic-bugs#138] opened 2022-07-13 00:49 UTC
#### 1.1. Description
Currently if you cast a spell with a cast time (Healing Touch for example) under the effect of a cast time modifier such as Predators Swiftness it has a low chance to proc Omen of Clarity
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Spec into Predatory Strikes
           2. Get a proc
           3. Cast Healing Touch
           4. repeat
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
During wrath using a cast-time spell with a modifier that made it instant somehow increased the chance for omen of clarity to proc, this can be observed in videos (Altho not the best indicator from a statistical PoV) but was also talked about in an old forum thread(below)
  #### 2.2 Source Material
https://www.mmo-champion.com/threads/681678-predator-s-swiftness-procs-omen-of-clarity-100

**Comment by JamminL** [comment] 2022-07-13 11:20
See https://github.com/JamminL/wotlk-classic-bugs/issues/66

**Comment by JamminL** [comment] 2022-07-13 11:35
After talking with the person who reported it, there's enough evidence to sustain this as a bug. I'll post the findings later today, I'll leave it as Pending for now

**Comment by JamminL** [comment] 2022-07-14 00:47
- EXPECTED

| SOURCE | PATCH |  Spellcast from Predator Swiftness  | OOC proc from those spells | 
| ------------- | ------------- |          ---: |          ---: |
| [Video ](http://www.warcraftmovies.com/movieview.php?id=132563) | 3.2.2 | 47 |  27 |
| [Video ](http://www.warcraftmovies.com/movieview.php?id=154129) | 3.3.3 | 55 |  34 |
| [Video starting from 3:05 (3.3.5) ](http://www.warcraftmovies.com/movieview.php?id=165811) | 3.3.5 | 18 |  13 |
| [Video ](http://www.warcraftmovies.com/movieview.php?id=154129) | 3.3.3 | 22 |  11
| **Total** | **-**| **142** | **85** |

- CURRENT

| SOURCE | PATCH |  Spellcast from Predator Swiftness  | OOC proc from those spells | 
| ------------- | ------------- |          ---: |          ---: |
| BETA               | 3.4.0.44644 | 37 |  0 |

Despite the small sample size, it's statistically impossible that OOC is working as intended, considering the estimated proc chance based on N= 142 is ~59,85%.

On the other post it seems like the proc chance is heavily increased for cat and bear forms, might be the case that the proc check was done before he left form?

Either way, if you'd like a bigger sample size, we can also arrange that, there's multiple warcraft logs from back in the day as well as other videos that support this

**Comment by JamminL** [comment] 2022-08-24 17:45
Fixed as of build 3.4.0.45264

**Closed by JamminL** 2022-08-24 17:45 UTC
Labels: Druid, BUG, Fixed
