### ISSUE TITLE
[BUG] Burning Determination buff not removed after being hit by a silence

### ISSUE THREAD

**Issue by peterderpirat** [JamminL/wotlk-classic-bugs#18] opened 2022-06-23 04:46 UTC
#### 1.1. Description
The burning determination buff which is triggered by the talent after being hit by a silence/interrupt is not currently removed by subsequent silences/interrupts.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Spec into Burning Determination and be hit by a silence (Arcane Torrent in this case)
           2. Once the buff is applied be hit by another silence (Spell Lock in this case)
           3. Observe how the spell lock is immuned but the buff stays on
  #### 1.3  Source Material
{Video, Posts, etc..}https://i.imgur.com/ML2Nvfm.jpeg
#### 2.1. Description
The Buff provided by the Burning Determination talent should be removed on the first silence that is immuned.
  #### 2.2 Source Material
{Video, Posts, etc..}
Tooltip states "you have a 100% chance to become immune to the **next** Interrupt or Silence mechanic.
Patch 3.3.3 states: This talent will no longer sometimes have its effect removed by the same spell that triggered it.

Implying that it should only immune 1 silence

**Comment by JamminL** [comment] 2022-06-23 09:46
Confirmed

**Comment by JamminL** [comment] 2022-07-03 07:09
So, after further testing it seems that burning determination aura does infact get removed on a second application of a kick or silence effect - **but only if the mage is casting when the kick/silence lands**

This means that if a shadow priest silences a mage with burning determination aura, and the mage isn't casting, then it immunes the silence but the burning determination stays.

This seems probably that's intended behavior so for now I'm marking this as NAB but leaving this up so maybe we get a referece check.

**Closed** 2022-07-04 14:41 UTC
Labels: Mage, BUG, Not a bug
