### ISSUE TITLE
[TEST-REQUEST] Druid 2p T3 and Revitalize

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#137] opened 2022-07-12 18:42 UTC
### Description
Note: Passing this along from Niche in the druid discord - his contact info is below.

The druid Dreamwalker set from original Naxxramas has a 2 piece bonus that generates resources (8 energy, 2 rage, 100 mana) for the target of the Rejuvenation spell. Revitalize is a talent in the Wrath restoration druid tree that seems inspired by the Dreamwalker bonus. Originally, Revitalize was called Replenish in 3.0 and worked for Rejuvenation only. In 3.1 it was changed to Revitalize and Wild Growth was added. Revitalize also generates resources, but the values are higher for rage and mana and runic power is added.

Modern druids have long wondered if the 2 set bonus and the talent would work together. After a search of archived blue posts and hours of scouring many threads from Elitist Jerks via archive.org as well as wowhead spell information pages, wowhead forum posts, mmochampion forums, restoration druid blogs from the time, and just general google searches, I have found no official or unofficial word regarding this behavior. Not many people playing druids in original Wrath had gear from original Naxxramas, or thought to try this combination, I suppose.

	Many original wow set bonuses had to be changed over time, like the paladin redemption bonus for Lay on Hands, or the druid and priest stormrage and transcendence mana regen bonuses. These were well documented by blue posts or patch notes. The behavior of Dreamwalker and Revitalize was a mystery we were eager to test on Wrath beta. A member of the druid discord, Gooses (Discord Veelers#7656), had 2 pieces of Dreamwalker and tested this for the community. Here are his results:

0/3 Revitalize, 2pT3, 579 Rejuv ticks 163 2pT3 procs
https://classic.warcraftlogs.com/reports/zQ6yM1jH3FpfPgLh/#fight=2

1/3 Revitalize, 2pT3, 557 Rejuv ticks 129 2pT3 procs | 0 Revitalize procs
https://classic.warcraftlogs.com/reports/LBx3n9FkwTzpWRVC

2/3 Revitalize, 2pT3, 568 Rejuv ticks 0 2pT3 procs | 61 Revitalize procs
https://classic.warcraftlogs.com/reports/cjwNQK3Xn9x6Cd8H

3/3 Revitalize, 2pT3, 563 Rejuv ticks 0 2pT3 procs | 80 Revitalize procs
https://classic.warcraftlogs.com/reports/dyFAf4TKgnD63Pz2

In summary, with the Dreamwalker gear equipped and no talents, he got the expected resource gains. With 1 of 3 points in Revitalize, things got interesting, giving no talent procs, only set bonus procs. Then it changes at 2 of 3 points to give no set bonus procs, but talent procs instead, this continues at 3 of 3 points.

So the question then is, is this intended behavior, a silent change made to the set bonus? Or is this a bug and both talent and set bonuses should work together? Nothing in the talent or set bonus language indicates they do not work together, and no patch note or blue post has spoken on this issue in the past. If there is notation on Blizzard’s side for this being an intended change and the public was not informed, that is fine. However, I would argue a different set of rules for this interaction be emplaced.

	With this behavior, a druid wishing to use the Dreamwalker bonus would have to reset their talents and not choose Revitalize. If the druid then wants Revitalize back for a different encounter, they would have to reset talents again (or use their secondary spec just for this interaction). This makes it difficult to use, but a more elegant way exists. Allowing the set bonus to take priority over the talent (even at 3/3) gives the player agency to use the set bonus when they want that behavior, and simply remove the set gear when they want the talent behavior. No talent reset needed or a dedicated secondary spec to solve the issue. The set bonus could even be updated to include a small amount of runic power so death knights aren’t left out, if you wish to head off the questions asking why Revitalize isn’t working on them with Dreamwalker equipped.

	For completeness, Wild Growth appears to retain the Revitalize talented behavior regardless of Dreamwalker bonus being equipped or not. This seems correct, as the set bonus is specific to Rejuvenation.

A new development on beta today shows a change in this behavior, but I do not believe it is due to any change related to the talent or set bonus, but due to dual specialization. Gooses tests the T3 interaction every time there is a new beta build, and his secondary specialization is balance for questing. Today he logged on beta to test this and was balance, he equipped the Dreamwalker pieces then activated his restoration talents, including 3/3 Revitalize, and began testing. This was the behavior he experienced:

Runic Power:  T3 prevents Revitalize from RJ, but WG works correctly. No T3 working as intended for both spells.

Mana/Rage/Energy: T3 procs on RJ, but Revitalize no longer functions. WG procs Revitalize as expected. T3 off Revitalize functions as intended for both spells.

	Here is a video of the change in behavior: https://streamable.com/hmvv9d At the start he has the talent and set bonus, casts a Rejuvenation and gets a proc from Revitalize. He then changes to balance talents, casts another Rejuvenation and begins changing back to restoration talents. The spell he cast while balance procs the set bonus, then, while restoration he casts another Rejuvenation right at the end of the video, and the tick gives him a set bonus proc, not a Revitalize proc. Despite this only showing for the last few seconds of the video, this appears to be the continuous behavior after changing talents to Restoration while wearing the Dreamwalker set bonus, giving set bonus procs instead of talent procs. So one way or another, this needs to be fixed to maintain consistent behavior.

—-

Implications of using this set bonus in Wrath Classic

	Many high performance guilds use every edge they can get, and this set bonus is particularly strong for energy based characters, but still useful for rage and mana characters. If the bonus is allowed to work in full alongside the talent, it would reward those who acquired the gear and kept it. In practice, the items have lower stats than Wrath items, so you give up personal power to give resources to others. This feels good from both a role playing point of view and also for competitive raiding, self sacrifice for the good of the team. Giving players the choice is also good.

	On the other hand, the Dreamwalker gear will no longer be available once Wrath Classic is live, so some druids seeking to join high performance raids may be at a disadvantage for access if those guilds feel the bonus is required. Even if only one top guild does this, there will be plenty of copycats that will institute it, and that is how the meta is shaped. It also potentially removes gear upgrades from 2 slots for the entire expansion, which is counter to WoW’s design of constantly upgrading gear to be more powerful.

	In the end, I believe allowing the set bonus to work in full alongside the talent is not good for the game, however we have no documented reason as to why they shouldn’t, so I can’t disagree with those saying it should work together. The current beta behavior is workable, which effectively disallows use of the set bonus, since all serious restoration druids will use Revitalize. I would prefer my change in priority to give those who want to use the set bonus selectively, the ability to do so without having a dedicated secondary specialization for it. Most of all, we’d just like to know Blizzard’s intention for the interaction.

Thank you for your time,

Niche
(Discord Niche#8642)

**Comment by Aggrend** [comment] 2022-08-12 23:31
Closing this as Not a Bug. This matches 3.3.5 reference.

**Closed** 2022-08-12 23:32 UTC
Labels: Druid, Not a Bug
