### ISSUE TITLE
[BUG] Hunter Auto shot resets melee swing timer. Melee swing does not reset auto shot timer.

### ISSUE THREAD

**Issue by BradBlondebeard** [JamminL/wotlk-classic-bugs#81] opened 2022-06-29 16:59 UTC
#### 1.1. Description
Currently in beta a hunter's auto shot resets their melee swing timer. Melee swings do not reset the auto shot swing timer. 

  #### 1.2. How to Reproduce
           1. Use Auto Shot
           2. Quickly go into melee range and either use raptor strike or start attack. You will find that the melee swing does not come out instantly like in tbcc.
           3. Start in melee range and swing your melee weapon
           4. Quickly go ranged and use auto shot. You will see auto shot will cast quickly, with a slight delay because of auto cast time and possibly retry timer.
  #### 1.3  Source Material
Clip of Skinnay showing the above behavior:
https://streamable.com/zwwcxs

#### 2.1. Description
Uncertain how the behavior was in original Wrath of the Lich King. 
Looking at a contemporary video from Kripparrian suggests the current beta behavior may be correct. I found a couple instances where Kripp moved into melee range shortly after shooting an auto shot, his melee weapon unsheathed, but no melee swing occurred. I also found a clip where Kripp melee swung, causing his swing timer addon to start a new swing, but then auto shot before the bar was completely filled. I have not been able to find a clear example of a melee swing followed almost immediately by an auto shot.
  #### 2.2 Source Material
Video 1: 
https://www.youtube.com/watch?v=RtkraBQbpgI&t=492s
1. Kripp walks to the top of a tower
2. Kripp targets warlock
3. Kripp casts auto shot
4. Kripp casts explosive shot
5. Auto Shot hits for 1708
6. Explosive shot crits for 2767
7. Kripp walks into melee range
8. Kripp's melee weapon unsheathes
9. Kripp casts kill command, causing his arms to move forward in the casting animation
10. Explosive shot ticks for 1190
11. Kripp jumps out of melee range
12. Explosive shot ticks for 1191
13. Kripp casts scatter shot
14. Scatter shot hits for 854
15. Kripp runs down the ramp
16. Kripp casts explosive shot
17. Kripp attempts to cast but gets line of sight error
18. Explosive shot tick gets fully absorbed
19. Kripp casts aimed shot
20. Aimed shot hits for 1096
21. Kripp casts auto shot
22. Auto shot crits for 3756
23. Explosive shot tick hits for 1096
24. Kripp runs into melee range
25. Kripps melee weapon unsheathes
26. Explosive shot tick crits for 2841
27. Kripp runs back down the ramp
28. Kripp casts auto shot
29. Auto shot crits for 3729
30. Kripp casts explosive shot
31. Explosive shot crits for 2910
32. Kripp run towards target
33. Kripp's melee weapon unsheathes
34. Kripp turns and runs to the left of warlock
35. Warlock dies

Can't see exactly what killed the warlock. Explosive shot would still be ticking, and there is no melee swing animation.

Video 2:
https://www.youtube.com/watch?v=RtkraBQbpgI&t=490s
1. Warrior charges Kripp
2. Kripp swings melee weapon
3. Kripp's swing timer addon resets
4. Melee attack hits for 3740
5. Kripp casts disengage
6. Kripp uses trinket
7. Kripp casts explosive shot
8. Kripp casts auto shot (before the swing timer addon is filled)
9. Auto shot crits for 3872
10. Explosive shot tick crits for 4722
11. Kripp casts aimed shot
12. Aimed shot crits for 5363
13. Kripp casts scatter shot
14. Warrior dies, scatter shot damage not shown.

**Comment by caccavale** [comment] 2022-06-29 20:48
My hunch here is Auto Shot and Steady Shot are counting as hard casted spells due to their cast times and thus are resetting melee swing.

**Comment by watchyoursixx** [comment] 2022-07-04 02:20
https://youtu.be/2y9qqxJOcVc?t=111

some evidence of it behaving without resets in 3.3.5 timing, around 1:50 mark. Shoot white then melee white within 1 sec of each other.

**Comment by chloanne** [comment] 2022-07-13 05:57
https://youtu.be/t9Gs6RQX1mo?t=278

Some additional evidence in a lower level pvp video. There is a blocked white auto shot followed directly by a blocked white melee attack around half a second later. Another blocked ranged shot into a melee hit happens around 10 seconds later in the same clip.

**Comment by watchyoursixx** [comment] 2022-08-04 00:20
Unfortunately the last 2 videos have since been found to be invalid - AV vid is from eternal-wow pserver and the other vid looks to be from another pserver given the text printed near the beginning of joins/leaves in 2s and their ratings lol.

Currently on the beta - there is a new interaction with this where melee delays the next ranged attack. This is indeed unintended. However, speaking with Aggrend the original interaction of the beta is "Not a bug" and behaved this way in original wrath 3.3.5. This matches the fact we couldn't find any evidence (aside from 2 pserver vids that looked real). He even said he intended to post here NAB but hadn't got to it yet.

I'm going to go ahead and close this as NAB. If something comes up that disproves it somehow, I can re-open it.

**Closed by watchyoursixx** 2022-08-04 00:20 UTC
Labels: Hunter, BUG

**Comment by miley-kingofweebs** [comment] 2022-08-04 04:02
https://youtu.be/OIdHrQMYjOQ?t=259

I'm not sure on how valid this video is, but supposedly it's from the WotLK prepatch in 2008.  There a lot of times where the guy will shoot an auto shot and then walk into melee spamming his Raptor Strike, but it doesn't go off.  It's easiest to see at 4:19, you can see the auto shot and silencing shot go out, he runs into melee range spamming Raptor Strike, and leaves melee range before a Raptor ever comes out.

**Comment by chloanne** [comment] 2022-08-05 04:27
> Currently on the beta - there is a new interaction with this where melee delays the next ranged attack. This is indeed unintended. However, speaking with Aggrend the original interaction of the beta is "Not a bug" and behaved this way in original wrath 3.3.5. This matches the fact we couldn't find any evidence (aside from 2 pserver vids that looked real). He even said he intended to post here NAB but hadn't got to it yet.

Is there another bug tracking this "new interaction", or should this issue be re-opened to track that fix?

**Comment by Aggrend** [comment] 2022-08-13 00:57
Wanted to finally put a pin in this, even though the issue is already closed. 

We had another bug that I wanted to validate was fixed first before posting ([that bug was Slam resetting swing timer, which will be resolved as of the 8/17 beta build](https://github.com/magey/wotlk-warrior/issues/19)), just in case that fix somehow impacted this and caused more research or fixes to be needed.

As noted above, this is correct behavior. Per the engineer who fixed the slam issue and dug into this:

Intended Wrath behavior:
- Performing a melee attack resets your ranged swing timer.
- Performing an Auto Shot resets your melee swing timer.
- Arcane Shot and other abilities are NOT affected. Casting Arcane Shot without doing an Auto Shot does not reset your melee swing timer.
