### ISSUE TITLE
[#SomeChanges Suggestion] Remove Enormous Melee Range from Teleporter Backfires

### ISSUE THREAD

**Issue by where-fore** [JamminL/wotlk-classic-bugs#344] opened 2022-08-24 04:48 UTC
### 1. Is your feature request related to a problem? Please describe.

If you cast either of the TBC engineering transporters, Toshley Station (Gnomish) or Area 52 (Goblin), you have a chance to get a random debuff from a certain library. Some of these debuffs can increase your player's hitbox size, and thus melee range. While the teleporters normally have a 4 hour cooldown, you can bypass this cooldown by force closing the game application right before the cast finishes - granting you a (chance at a) size increasing debuff. The 4 different size increasing debuffs all stack together, providing an enormous boost to melee attack range.

This melee range can be so comically large, players with enough of these debuffs were able to melee attack Felmyst during Felmyst's air phase, simply by being big enough to reach the dragon from the ground. There are countless other gameplay uses for having a huge melee range - being able to attack enemies even though they have rooted you in an awkward place - and even more notably in pvp, where some of the debuffs are still available.

Below you can see an image of my enormous Human rogue (transformed into a Tauren) standing at maximum melee range from an ogre, who is attacking a regular player at their maximum melee range. My super-sized melee range is nearly 3 times as long as a regular melee range.

![image](https://user-images.githubusercontent.com/108002636/186329463-d5792fdf-b56c-4b24-bbc7-96cc4059714f.png)

While this is a fun idea, and has been quite entertaining to hear about the shennanigans people have gotten up to by having an enormous attack range, the process of getting these debuffs can be a pain - and even be harmful to other players of the game. The debuffs are random, thus requiring many tries of simply casting a spell and Alt-F4-ing your game, taking sometimes up to an hour to gather the full selection of debuffs. Further, there are some unwanted debuffs you can get which reduce your size. There are two processes to get rid of these unwanted debuffs:
- (Gnomish Engineering Required) Use a World Enlarger, this will simply clear your debuffs.
- (No Requirements) Join an Arena match, where these specific unwanted debuffs happen to be removed upon entry, and then leave the arena match immediately, to preserve the time left on the rest of your debuffs.

When considering performance-oriented players, they are now faced with an unfortunate dilemma - go through the dull process of gathering all the appropriate debuffs before every raid they are interested in (potentially ruining a few Arena matches along the way), or willingly choose not to arrive to raid with the most power they can.

While the gain from having an enormous melee range is situational at best, it can be so incredibly powerful in those situations, that given this option is available, it will be utilized heavily amongst performance-oriented players, as it has been throughout Sunwell Plateau speed runs in TBC. Given that this is powerful, unintentional, and painful to setup, I propose changing this interaction to solve this dilemma for performance-oriented players.

### 1.1 Describe the solution you'd like
Suggestions to change this interaction:

- Prevent the debuffs from stacking with each other. They seem to be designed as a fun quirk of a 4-hour cooldown item, not a powerful-infinitely-stacking debuff machine, and just one debuffs is generally not enough size to make a meaningful difference in gameplay.
- Prevent the debuffs from affecting Engineers of a certain level, or characters of a certain level. Maybe you are too powerful for a puny Outland technology to affect you?
- Reveal the precence of these debuffs to the Combat Log (as was done for countless other buffs and consumables), so Warcraft Logs can ban the interaction themselves, in the interest of performance-oriented players competing on that website.
- Flag these debuffs under a system similar to Season of Mastery's World Buff Removal system - clear these upon entering a raid instance. This would keep the fun interaction available for all players, just not during raid encounters.
- Somehow remove the ability to gain the Teleporter debuffs from force closing the game before the cast finishes. This sounds like a scary code change that can be avoided with the above suggestions.

If this interaction is intended to be kept in the game, then I would suggest removing the interactions with the Arena system - maybe flag all of the transporter debuffs to be removed upon entering an Arena.

### 1.2 Additional context

Thank you for your time.

**Comment by CharWS** [comment] 2022-08-24 04:54
duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/256

**Closed by CharWS** 2022-08-24 04:54 UTC
Labels: #SomeChanges Suggestion
