### ISSUE TITLE
[BUG] Deadly gear purchasable based on TBC arena ratings

### ISSUE THREAD

**Issue by Oliaxz** [JamminL/wotlk-classic-bugs#436] opened 2022-09-30 02:07 UTC
#### 1.1. Description
You can buy lvl 80 deadly gear with old tbc arena rating.

Please hot fix/remove the vendors, and remove deadly gear from peoples inventory before the season opens.

**Comment by Evolvee** [comment] 2022-09-30 09:38
Its just the honor items right?

If you reached the rating in tbc its safe to assume that you will in wotlk too, so removing it from players without any compensation (especially since its a blizz's fuckup, _as usual_) seems like an overkill...

_Inb4 they compensate the honor automatically but the to the honor cap they screw everyone in the process._

**Comment by Oliaxz** [comment] 2022-09-30 10:09
> Its just the honor items right?
> 
> If you reached the rating in tbc its safe to assume that you will in wotlk too, so removing it from players without any compensation (especially since its a blizz's fuckup, _as usual_) seems like an overkill...
> 
> _Inb4 they compensate the honor automatically but due to the honor cap they screw everyone in the process._

Its safe to assume it works on main set, but people have no arena pts. 

The issue is that its not fair for people that didnt achieve the rating and want to buy pvp gea, because they are limited by the honor cap. Those people have no choice but to spend their honor pts on sub-par items/non deadly gear until they grind out the rating requirement after season open.

Its relatively unknown for now, and bliz must take action extremely fast if they want to prevent backlash. There were similar issue with pvp rings in tbc/ranking in som, and i remember everyone freaking out and some quitting over it.

**Comment by dariuzsdk** [comment] 2022-09-30 16:01
"The issue is that its not fair for people that didnt achieve the rating and want to buy pvp gear, because they are limited by the honor cap."

As a DK I had no previous TBC ranked arena rating but I am able to purchase everything but the boots and belt - not sure if this part is true

**Comment by Oliaxz** [comment] 2022-09-30 16:22
> "The issue is that its not fair for people that didnt achieve the rating and want to buy pvp gear, because they are limited by the honor cap."
> 
> As a DK I had no previous TBC ranked arena rating but I am able to purchase everything but the boots and belt - not sure if this part is true

Could it be that they removed rating requirement on most deadly offpiece?

According to the info i could find, this should be the requirements.
Deadly Gear : 
Waist : 62000 HP - 1630 CR
Wrists : 39400 HP - 1660 CR
Feet : 62000 HP - 1720 CR
Neck : 47400 HP - 1600 CR
Finger : 47400 HP - 1690 CR
Back : 47400 HP - 1750 CR
Battlemaster : 62000 HP - 1800 CR

Head : 2250 AP - 1990 CR
Shoulders : 1750 AP - 2050 CR
Chest : 2250 AP - 1870 CR
Legs : 2250 AP - 1810 CR
Hands : 1350 AP - 1750 CR
2H/Gun/Crossbow/Bow : 4500 AP - 1930 CR
Idol/Libram/Wand/Thrown : 1200 AP - 1930 CR 
Shield : 2250 AP - 1930 CR
OH : 1350 AP - 1930 CR
MH : 3150 AP - 1930 CR

**Comment by Oliaxz** [comment] 2022-09-30 20:19
> https://imgur.com/a/rOPmq1n - What I'm seeing atm with no previous rate

Thank you! 

So it looks like this is not a bug, but rather a custom change from bliz. They removed rating requirement on all the deadly offpieces, except belt and boots, which are now 1300 and 1400.

This is a good change imo. The old rating req are not in line with today's difficulty. Also, a lot of people already have all the deadly offpiece by spamming wintergrasp, so dont make any change i guess. Sorry for the confusion.

**Comment by JamminL** [comment] 2022-09-30 20:22
This is still bugged for boots and belt. People with tbc rating can purchase these.

**Comment by watchyoursixx** [comment] 2023-01-19 02:00
dont know if this was ever fixed, but closing since season 5 is over and *hopefully* this still can't happen with season 6. Can reopen if instances are found of it being still the case

**Closed by watchyoursixx** 2023-01-19 02:00 UTC
Labels: General, BUG
