### ISSUE TITLE
[BUG] Pets losing Health after dismounting from Flying Mount (after flying not ground)

### ISSUE THREAD

**Issue by nistra123** [JamminL/wotlk-classic-bugs#490] opened 2022-10-22 10:03 UTC
#### 1.1. Description
When you mount up on any Flying mount and start flying around, drop to the ground and dismount your pet loses health and doesnt get healed back up. When you fly from combat to combat it gets to the point where youre pot drops to 1% and dies to the first hit after sending it to attack a NPC. That is obviously really annoying.

  #### 1.2. How to Reproduce
         Play Warlock or Hunter and Summon a Pet.
           1. Mount on your Flying mount.
           2. Fly in the Air 
           3. Dismount and watch your Pet HP.

  #### 1.3  Source Material
https://www.youtube.com/watch?v=zFzeSc-g9ig&

### 2. Expected Behavior
Pet shouldn't lose hp.

**Comment by watchyoursixx** [comment] 2022-10-22 10:15
duplicate of #129 and also there's a fix in flight sometime soon

**Closed by watchyoursixx** 2022-10-22 10:15 UTC
Labels: Pending Approval
