### ISSUE TITLE
[BUG]Dancing Rune Weapon Diseases start resisting after duration ends

### ISSUE THREAD

**Issue by MHMabrito** [JamminL/wotlk-classic-bugs#652] opened 2023-04-07 13:15 UTC
1.    Current Behavior

When Dancing Rune Weapon despawns, its diseases starts resisting, doing significantly less damage.

1.1.    Description

You can use Dancing Rune Weapon to apply an extra set of diseases. However, when your Dancing Rune Weapon duration ends, these diseases starts resisting, reducing in damage significantly.

1.2.    How to Reproduce

1.    Have a Death Knight cast Dancing Rune Weapon on a target and then use Plague Strike + Icy Touch to apply an extra set of diseases.
2.    Watch the damage of these diseases while Dancing Rune Weapon is up.
3.    Notice that when Dancing Rune Weapon fades, the damage is significantly reduced, and isn’t even visible on screen.
4.    Go into your log/damage meter notice that the extra diseases starts doing about ¼ of the damage after Dancing Rune Weapon fades.

1.3.    Source Material

https://youtu.be/9MQaifIn_k4?t=185
https://classic.warcraftlogs.com/reports/TBWXfmzd7N8cPxnv/#fight=last&type=damage-done&source=6 (Diseases resisting on dummy)
https://classic.warcraftlogs.com/reports/qYQwfrWm6GcFgP1b#fight=68&type=damage-done&source=16 (Diseases resisting in raid)

2.    Expected behavior.

Your extra diseases should still be doing full damage when your Dancing Rune Weapon fades

**Comment by CharWS** [comment] 2023-04-07 16:55
Duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/460

**Closed by CharWS** 2023-04-07 16:55 UTC
Labels: Pending Approval
