### ISSUE TITLE
[BUG]Dancing Rune Weapon scaling is not accurate to the tooltip.

### ISSUE THREAD

**Issue by MHMabrito** [JamminL/wotlk-classic-bugs#648] opened 2023-04-07 12:43 UTC
1.    Current Behavior

The special attacks of the ‘Dancing Rune Weapon’ ability are not scaling properly. 

1.1.    Description

According to the tooltip, Dancing Rune Weapon should duplicate any ability you cast for 50% of the damage. However, in reality, it’s closer to 25%.

1.2.    How to Reproduce

1.    Have a Death Knight cast Dancing Rune Weapon on a target.
2.    Go inside your log or damage meter and take a look at the damage breakdown of your Dancing Rune Weapon.
3.    Notice that abilities such as ‘Heart Strike’, ‘Death Strike’ and ‘Death Coil’ are doing nowhere near the 50% promised by the tooltip.

1.3.    Source Material
     https://youtu.be/9MQaifIn_k4?t=100

2.    Expected behavior.

Dancing Rune Weapon’s Special Attacks should scale in the same way as its autos. They should gain benefit from Blood Presence, which they currently do not. They should gain benefit from Unholy Frenzy, which they currently do not. At this time, the specials only get benefit from Attack Power, as well as a few select talents. If things are left as they are, the Dancing Rune Weapon Specials will be doing less than 20% of the main ability by the end of the expansion.

**Comment by CharWS** [comment] 2023-04-07 16:54
Duplicate of https://github.com/JamminL/wotlk-classic-bugs/issues/394 if you have further info to add to that report please add it there

**Closed by CharWS** 2023-04-07 16:54 UTC
Labels: Pending Approval
